// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FieldCondition defines when a field should be visible (depends on another field's value).
 */
export class FieldCondition {
    /**
     * Creates a new FieldCondition instance.
     * @param {Partial<FieldCondition>} [$$source = {}] - The source object to create the FieldCondition.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * the field key to watch
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * show this field when the watched field equals this value
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldCondition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FieldCondition}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FieldCondition(/** @type {Partial<FieldCondition>} */($$parsedSource));
    }
}

/**
 * NotifyChannelFieldMeta describes a single form field for a notify channel type.
 */
export class NotifyChannelFieldMeta {
    /**
     * Creates a new NotifyChannelFieldMeta instance.
     * @param {Partial<NotifyChannelFieldMeta>} [$$source = {}] - The source object to create the NotifyChannelFieldMeta.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * params key, e.g. "endpoint", "token"
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * display label, e.g. "服务器地址"
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * input type: "text", "password", "url", "number", "select"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("placeholder" in $$source)) {
            /**
             * placeholder text
             * @member
             * @type {string}
             */
            this["placeholder"] = "";
        }
        if (!("required" in $$source)) {
            /**
             * whether the field is required
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (!("hint" in $$source)) {
            /**
             * optional hint below the field
             * @member
             * @type {string}
             */
            this["hint"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * optional default value
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("options" in $$source)) {
            /**
             * options for "select" type fields
             * @member
             * @type {SelectOption[]}
             */
            this["options"] = [];
        }
        if (!("dependsOn" in $$source)) {
            /**
             * show this field only when condition is met
             * @member
             * @type {FieldCondition | null}
             */
            this["dependsOn"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifyChannelFieldMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotifyChannelFieldMeta}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField7_0($$parsedSource["options"]);
        }
        if ("dependsOn" in $$parsedSource) {
            $$parsedSource["dependsOn"] = $$createField8_0($$parsedSource["dependsOn"]);
        }
        return new NotifyChannelFieldMeta(/** @type {Partial<NotifyChannelFieldMeta>} */($$parsedSource));
    }
}

/**
 * NotifyChannelTypeMeta describes a notification channel type and its form fields.
 */
export class NotifyChannelTypeMeta {
    /**
     * Creates a new NotifyChannelTypeMeta instance.
     * @param {Partial<NotifyChannelTypeMeta>} [$$source = {}] - The source object to create the NotifyChannelTypeMeta.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * e.g. "gotify"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * human-readable label, e.g. "Gotify"
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * form fields for this type
             * @member
             * @type {NotifyChannelFieldMeta[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifyChannelTypeMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotifyChannelTypeMeta}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        return new NotifyChannelTypeMeta(/** @type {Partial<NotifyChannelTypeMeta>} */($$parsedSource));
    }
}

/**
 * SelectOption defines an option item in a select/dropdown field.
 */
export class SelectOption {
    /**
     * Creates a new SelectOption instance.
     * @param {Partial<SelectOption>} [$$source = {}] - The source object to create the SelectOption.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * display text, e.g. "Access Token"
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * option value, e.g. "token"
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SelectOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectOption(/** @type {Partial<SelectOption>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SelectOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FieldCondition.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = NotifyChannelFieldMeta.createFrom;
const $$createType5 = $Create.Array($$createType4);
