// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ReleaseAsset mirrors a GitHub release asset.
 */
export class ReleaseAsset {
    /**
     * Creates a new ReleaseAsset instance.
     * @param {Partial<ReleaseAsset>} [$$source = {}] - The source object to create the ReleaseAsset.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("browser_download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["browser_download_url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseAsset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReleaseAsset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseAsset(/** @type {Partial<ReleaseAsset>} */($$parsedSource));
    }
}

/**
 * UpdateInfo holds the result of a release check.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("hasUpdate" in $$source)) {
            /**
             * HasUpdate indicates whether a newer release exists.
             * @member
             * @type {boolean}
             */
            this["hasUpdate"] = false;
        }
        if (!("currentVersion" in $$source)) {
            /**
             * CurrentVersion is the running app's version (GitCommit, truncated to 7 chars).
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * LatestVersion is the latest release tag name.
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("latestUrl" in $$source)) {
            /**
             * LatestURL is the HTML URL of the latest release page.
             * @member
             * @type {string}
             */
            this["latestUrl"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * PublishedAt is when the latest release was published.
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Assets lists downloadable assets (browser_download_url + name).
             * @member
             * @type {ReleaseAsset[] | undefined}
             */
            this["assets"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField5_0($$parsedSource["assets"]);
        }
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ReleaseAsset.createFrom;
const $$createType1 = $Create.Array($$createType0);
