// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * BWSActivity represents a single BWS activity parsed from the API response.
 */
export class BWSActivity {
    /**
     * Creates a new BWSActivity instance.
     * @param {Partial<BWSActivity>} [$$source = {}] - The source object to create the BWSActivity.
     */
    constructor($$source = {}) {
        if (!("ReserveID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ReserveID"] = 0;
        }
        if (!("ActTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ActTitle"] = "";
        }
        if (!("ReserveBeginTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ReserveBeginTime"] = 0;
        }
        if (!("ActBeginTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ActBeginTime"] = 0;
        }
        if (!("State" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["State"] = 0;
        }
        if (!("DescribeInfo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DescribeInfo"] = "";
        }
        if (!("ReserveDate" in $$source)) {
            /**
             * the date key this activity belongs to (e.g. "20250711")
             * @member
             * @type {string}
             */
            this["ReserveDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BWSActivity instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BWSActivity}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BWSActivity(/** @type {Partial<BWSActivity>} */($$parsedSource));
    }
}

/**
 * BWSReservationData aggregates all parsed reservation information
 * needed by the BWS task to locate the correct ticket for an activity.
 */
export class BWSReservationData {
    /**
     * Creates a new BWSReservationData instance.
     * @param {Partial<BWSReservationData>} [$$source = {}] - The source object to create the BWSReservationData.
     */
    constructor($$source = {}) {
        if (!("TicketMapping" in $$source)) {
            /**
             * TicketMapping maps date (e.g. "20250711") → ticket_no
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["TicketMapping"] = {};
        }
        if (!("TicketInfo" in $$source)) {
            /**
             * TicketInfo maps date → full ticket info (for display)
             * @member
             * @type {{ [_ in string]?: BWSTicketInfo }}
             */
            this["TicketInfo"] = {};
        }
        if (!("ActivityMapping" in $$source)) {
            /**
             * ActivityMapping maps activity_id → BWSActivity (for quick lookup)
             * @member
             * @type {{ [_ in `${number}`]?: BWSActivity | null }}
             */
            this["ActivityMapping"] = {};
        }
        if (!("ReservedIDs" in $$source)) {
            /**
             * ReservedIDs is the set of activity IDs the user has already reserved
             * @member
             * @type {{ [_ in `${number}`]?: boolean }}
             */
            this["ReservedIDs"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BWSReservationData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BWSReservationData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TicketMapping" in $$parsedSource) {
            $$parsedSource["TicketMapping"] = $$createField0_0($$parsedSource["TicketMapping"]);
        }
        if ("TicketInfo" in $$parsedSource) {
            $$parsedSource["TicketInfo"] = $$createField1_0($$parsedSource["TicketInfo"]);
        }
        if ("ActivityMapping" in $$parsedSource) {
            $$parsedSource["ActivityMapping"] = $$createField2_0($$parsedSource["ActivityMapping"]);
        }
        if ("ReservedIDs" in $$parsedSource) {
            $$parsedSource["ReservedIDs"] = $$createField3_0($$parsedSource["ReservedIDs"]);
        }
        return new BWSReservationData(/** @type {Partial<BWSReservationData>} */($$parsedSource));
    }
}

/**
 * BWSTicketInfo represents a user's ticket for a specific date.
 */
export class BWSTicketInfo {
    /**
     * Creates a new BWSTicketInfo instance.
     * @param {Partial<BWSTicketInfo>} [$$source = {}] - The source object to create the BWSTicketInfo.
     */
    constructor($$source = {}) {
        if (!("Date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Date"] = "";
        }
        if (!("Ticket" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Ticket"] = "";
        }
        if (!("ScreenName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ScreenName"] = "";
        }
        if (!("SkuName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SkuName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BWSTicketInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BWSTicketInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BWSTicketInfo(/** @type {Partial<BWSTicketInfo>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const BuyerType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    Ordinary: 1,
    ForceRealName: 2,
};

export class ProjectInformation {
    /**
     * Creates a new ProjectInformation instance.
     * @param {Partial<ProjectInformation>} [$$source = {}] - The source object to create the ProjectInformation.
     */
    constructor($$source = {}) {
        if (!("ProjectID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ProjectID"] = "";
        }
        if (!("StartTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["StartTime"] = null;
        }
        if (!("EndTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["EndTime"] = null;
        }
        if (!("IsHotProject" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsHotProject"] = false;
        }
        if (!("IsForceRealName" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsForceRealName"] = false;
        }
        if (!("IsNeedContact" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsNeedContact"] = false;
        }
        if (!("IDBind" in $$source)) {
            /**
             * 0 = 无实名, 1 = 单人实名可买多张票（拆分下单）, 2 = 一票一实名
             * @member
             * @type {number}
             */
            this["IDBind"] = 0;
        }
        if (!("ProjectName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ProjectName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInformation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectInformation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectInformation(/** @type {Partial<ProjectInformation>} */($$parsedSource));
    }
}

export class RequestTokenAndPToken {
    /**
     * Creates a new RequestTokenAndPToken instance.
     * @param {Partial<RequestTokenAndPToken>} [$$source = {}] - The source object to create the RequestTokenAndPToken.
     */
    constructor($$source = {}) {
        if (!("RequestToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RequestToken"] = "";
        }
        if (!("PToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PToken"] = "";
        }
        if (!("GaiaToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["GaiaToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestTokenAndPToken instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RequestTokenAndPToken}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestTokenAndPToken(/** @type {Partial<RequestTokenAndPToken>} */($$parsedSource));
    }
}

/**
 * SaleFlagInfo represents a ticket sale flag (stock count + display text).
 */
export class SaleFlagInfo {
    /**
     * Creates a new SaleFlagInfo instance.
     * @param {Partial<SaleFlagInfo>} [$$source = {}] - The source object to create the SaleFlagInfo.
     */
    constructor($$source = {}) {
        if (!("number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["number"] = 0;
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaleFlagInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaleFlagInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaleFlagInfo(/** @type {Partial<SaleFlagInfo>} */($$parsedSource));
    }
}

/**
 * SaleTimeRange represents the start/end time window for a ticket's sale period.
 */
export class SaleTimeRange {
    /**
     * Creates a new SaleTimeRange instance.
     * @param {Partial<SaleTimeRange>} [$$source = {}] - The source object to create the SaleTimeRange.
     */
    constructor($$source = {}) {
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["start"] = null;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["end"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaleTimeRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaleTimeRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaleTimeRange(/** @type {Partial<SaleTimeRange>} */($$parsedSource));
    }
}

export class TicketBuyer {
    /**
     * Creates a new TicketBuyer instance.
     * @param {Partial<TicketBuyer>} [$$source = {}] - The source object to create the TicketBuyer.
     */
    constructor($$source = {}) {
        if (!("BuyerType" in $$source)) {
            /**
             * @member
             * @type {BuyerType}
             */
            this["BuyerType"] = BuyerType.$zero;
        }
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("Tel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Tel"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketBuyer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketBuyer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketBuyer(/** @type {Partial<TicketBuyer>} */($$parsedSource));
    }
}

export class TicketSkuScreenID {
    /**
     * Creates a new TicketSkuScreenID instance.
     * @param {Partial<TicketSkuScreenID>} [$$source = {}] - The source object to create the TicketSkuScreenID.
     */
    constructor($$source = {}) {
        if (!("screenId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["screenId"] = 0;
        }
        if (!("skuId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skuId"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desc"] = "";
        }
        if (!("price" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["price"] = 0;
        }
        if (!("flags" in $$source)) {
            /**
             * @member
             * @type {SaleFlagInfo}
             */
            this["flags"] = (new SaleFlagInfo());
        }
        if (!("saleStat" in $$source)) {
            /**
             * @member
             * @type {SaleTimeRange}
             */
            this["saleStat"] = (new SaleTimeRange());
        }
        if (!("eventTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["eventTime"] = null;
        }
        if (!("buyLimit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["buyLimit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketSkuScreenID instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketSkuScreenID}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType7;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField5_0($$parsedSource["flags"]);
        }
        if ("saleStat" in $$parsedSource) {
            $$parsedSource["saleStat"] = $$createField6_0($$parsedSource["saleStat"]);
        }
        return new TicketSkuScreenID(/** @type {Partial<TicketSkuScreenID>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = BWSTicketInfo.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = BWSActivity.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = SaleFlagInfo.createFrom;
const $$createType8 = SaleTimeRange.createFrom;
