// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: captcha.proto

package captcha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClickService_Solve_FullMethodName        = "/captcha.ClickService/Solve"
	ClickService_GetCS_FullMethodName        = "/captcha.ClickService/GetCS"
	ClickService_GetType_FullMethodName      = "/captcha.ClickService/GetType"
	ClickService_GetNewCSArgs_FullMethodName = "/captcha.ClickService/GetNewCSArgs"
	ClickService_CalculateKey_FullMethodName = "/captcha.ClickService/CalculateKey"
	ClickService_GenerateW_FullMethodName    = "/captcha.ClickService/GenerateW"
	ClickService_Verify_FullMethodName       = "/captcha.ClickService/Verify"
	ClickService_Version_FullMethodName      = "/captcha.ClickService/Version"
)

// ClickServiceClient is the client API for ClickService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClickServiceClient interface {
	// Solve runs the full click pipeline.
	Solve(ctx context.Context, in *SolveGeetestCaptchaRequest, opts ...grpc.CallOption) (*SolveGeetestCaptchaResponse, error)
	// Individual steps for callers that need fine-grained control.
	GetCS(ctx context.Context, in *GetCSRequest, opts ...grpc.CallOption) (*GetCSResponse, error)
	GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error)
	GetNewCSArgs(ctx context.Context, in *GetNewCSArgsRequest, opts ...grpc.CallOption) (*GetNewCSArgsResponse, error)
	CalculateKey(ctx context.Context, in *CalculateKeyRequest, opts ...grpc.CallOption) (*CalculateKeyResponse, error)
	GenerateW(ctx context.Context, in *GenerateWRequest, opts ...grpc.CallOption) (*GenerateWResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type clickServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClickServiceClient(cc grpc.ClientConnInterface) ClickServiceClient {
	return &clickServiceClient{cc}
}

func (c *clickServiceClient) Solve(ctx context.Context, in *SolveGeetestCaptchaRequest, opts ...grpc.CallOption) (*SolveGeetestCaptchaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveGeetestCaptchaResponse)
	err := c.cc.Invoke(ctx, ClickService_Solve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickServiceClient) GetCS(ctx context.Context, in *GetCSRequest, opts ...grpc.CallOption) (*GetCSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCSResponse)
	err := c.cc.Invoke(ctx, ClickService_GetCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickServiceClient) GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTypeResponse)
	err := c.cc.Invoke(ctx, ClickService_GetType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickServiceClient) GetNewCSArgs(ctx context.Context, in *GetNewCSArgsRequest, opts ...grpc.CallOption) (*GetNewCSArgsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewCSArgsResponse)
	err := c.cc.Invoke(ctx, ClickService_GetNewCSArgs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickServiceClient) CalculateKey(ctx context.Context, in *CalculateKeyRequest, opts ...grpc.CallOption) (*CalculateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateKeyResponse)
	err := c.cc.Invoke(ctx, ClickService_CalculateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickServiceClient) GenerateW(ctx context.Context, in *GenerateWRequest, opts ...grpc.CallOption) (*GenerateWResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateWResponse)
	err := c.cc.Invoke(ctx, ClickService_GenerateW_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, ClickService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, ClickService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClickServiceServer is the server API for ClickService service.
// All implementations must embed UnimplementedClickServiceServer
// for forward compatibility.
type ClickServiceServer interface {
	// Solve runs the full click pipeline.
	Solve(context.Context, *SolveGeetestCaptchaRequest) (*SolveGeetestCaptchaResponse, error)
	// Individual steps for callers that need fine-grained control.
	GetCS(context.Context, *GetCSRequest) (*GetCSResponse, error)
	GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error)
	GetNewCSArgs(context.Context, *GetNewCSArgsRequest) (*GetNewCSArgsResponse, error)
	CalculateKey(context.Context, *CalculateKeyRequest) (*CalculateKeyResponse, error)
	GenerateW(context.Context, *GenerateWRequest) (*GenerateWResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedClickServiceServer()
}

// UnimplementedClickServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClickServiceServer struct{}

func (UnimplementedClickServiceServer) Solve(context.Context, *SolveGeetestCaptchaRequest) (*SolveGeetestCaptchaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedClickServiceServer) GetCS(context.Context, *GetCSRequest) (*GetCSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCS not implemented")
}
func (UnimplementedClickServiceServer) GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetType not implemented")
}
func (UnimplementedClickServiceServer) GetNewCSArgs(context.Context, *GetNewCSArgsRequest) (*GetNewCSArgsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewCSArgs not implemented")
}
func (UnimplementedClickServiceServer) CalculateKey(context.Context, *CalculateKeyRequest) (*CalculateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateKey not implemented")
}
func (UnimplementedClickServiceServer) GenerateW(context.Context, *GenerateWRequest) (*GenerateWResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateW not implemented")
}
func (UnimplementedClickServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedClickServiceServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedClickServiceServer) mustEmbedUnimplementedClickServiceServer() {}
func (UnimplementedClickServiceServer) testEmbeddedByValue()                      {}

// UnsafeClickServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClickServiceServer will
// result in compilation errors.
type UnsafeClickServiceServer interface {
	mustEmbedUnimplementedClickServiceServer()
}

func RegisterClickServiceServer(s grpc.ServiceRegistrar, srv ClickServiceServer) {
	// If the following call panics, it indicates UnimplementedClickServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClickService_ServiceDesc, srv)
}

func _ClickService_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveGeetestCaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickServiceServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickService_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickServiceServer).Solve(ctx, req.(*SolveGeetestCaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickService_GetCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickServiceServer).GetCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickService_GetCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickServiceServer).GetCS(ctx, req.(*GetCSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickService_GetType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickServiceServer).GetType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickService_GetType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickServiceServer).GetType(ctx, req.(*GetTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickService_GetNewCSArgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewCSArgsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickServiceServer).GetNewCSArgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickService_GetNewCSArgs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickServiceServer).GetNewCSArgs(ctx, req.(*GetNewCSArgsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickService_CalculateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickServiceServer).CalculateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickService_CalculateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickServiceServer).CalculateKey(ctx, req.(*CalculateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickService_GenerateW_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickServiceServer).GenerateW(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickService_GenerateW_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickServiceServer).GenerateW(ctx, req.(*GenerateWRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClickService_ServiceDesc is the grpc.ServiceDesc for ClickService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClickService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "captcha.ClickService",
	HandlerType: (*ClickServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _ClickService_Solve_Handler,
		},
		{
			MethodName: "GetCS",
			Handler:    _ClickService_GetCS_Handler,
		},
		{
			MethodName: "GetType",
			Handler:    _ClickService_GetType_Handler,
		},
		{
			MethodName: "GetNewCSArgs",
			Handler:    _ClickService_GetNewCSArgs_Handler,
		},
		{
			MethodName: "CalculateKey",
			Handler:    _ClickService_CalculateKey_Handler,
		},
		{
			MethodName: "GenerateW",
			Handler:    _ClickService_GenerateW_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _ClickService_Verify_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _ClickService_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "captcha.proto",
}

const (
	SlideService_Solve_FullMethodName        = "/captcha.SlideService/Solve"
	SlideService_GetCS_FullMethodName        = "/captcha.SlideService/GetCS"
	SlideService_GetType_FullMethodName      = "/captcha.SlideService/GetType"
	SlideService_GetNewCSArgs_FullMethodName = "/captcha.SlideService/GetNewCSArgs"
	SlideService_CalculateKey_FullMethodName = "/captcha.SlideService/CalculateKey"
	SlideService_GenerateW_FullMethodName    = "/captcha.SlideService/GenerateW"
	SlideService_Verify_FullMethodName       = "/captcha.SlideService/Verify"
	SlideService_Version_FullMethodName      = "/captcha.SlideService/Version"
)

// SlideServiceClient is the client API for SlideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlideServiceClient interface {
	// Solve runs the full slide pipeline.
	Solve(ctx context.Context, in *SolveGeetestCaptchaRequest, opts ...grpc.CallOption) (*SolveGeetestCaptchaResponse, error)
	// Individual steps for callers that need fine-grained control.
	GetCS(ctx context.Context, in *GetCSRequest, opts ...grpc.CallOption) (*GetCSResponse, error)
	GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error)
	GetNewCSArgs(ctx context.Context, in *GetNewCSArgsRequest, opts ...grpc.CallOption) (*GetNewCSArgsResponse, error)
	CalculateKey(ctx context.Context, in *CalculateKeyRequest, opts ...grpc.CallOption) (*CalculateKeyResponse, error)
	GenerateW(ctx context.Context, in *GenerateWRequest, opts ...grpc.CallOption) (*GenerateWResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type slideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlideServiceClient(cc grpc.ClientConnInterface) SlideServiceClient {
	return &slideServiceClient{cc}
}

func (c *slideServiceClient) Solve(ctx context.Context, in *SolveGeetestCaptchaRequest, opts ...grpc.CallOption) (*SolveGeetestCaptchaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveGeetestCaptchaResponse)
	err := c.cc.Invoke(ctx, SlideService_Solve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slideServiceClient) GetCS(ctx context.Context, in *GetCSRequest, opts ...grpc.CallOption) (*GetCSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCSResponse)
	err := c.cc.Invoke(ctx, SlideService_GetCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slideServiceClient) GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTypeResponse)
	err := c.cc.Invoke(ctx, SlideService_GetType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slideServiceClient) GetNewCSArgs(ctx context.Context, in *GetNewCSArgsRequest, opts ...grpc.CallOption) (*GetNewCSArgsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewCSArgsResponse)
	err := c.cc.Invoke(ctx, SlideService_GetNewCSArgs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slideServiceClient) CalculateKey(ctx context.Context, in *CalculateKeyRequest, opts ...grpc.CallOption) (*CalculateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateKeyResponse)
	err := c.cc.Invoke(ctx, SlideService_CalculateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slideServiceClient) GenerateW(ctx context.Context, in *GenerateWRequest, opts ...grpc.CallOption) (*GenerateWResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateWResponse)
	err := c.cc.Invoke(ctx, SlideService_GenerateW_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slideServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, SlideService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slideServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, SlideService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlideServiceServer is the server API for SlideService service.
// All implementations must embed UnimplementedSlideServiceServer
// for forward compatibility.
type SlideServiceServer interface {
	// Solve runs the full slide pipeline.
	Solve(context.Context, *SolveGeetestCaptchaRequest) (*SolveGeetestCaptchaResponse, error)
	// Individual steps for callers that need fine-grained control.
	GetCS(context.Context, *GetCSRequest) (*GetCSResponse, error)
	GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error)
	GetNewCSArgs(context.Context, *GetNewCSArgsRequest) (*GetNewCSArgsResponse, error)
	CalculateKey(context.Context, *CalculateKeyRequest) (*CalculateKeyResponse, error)
	GenerateW(context.Context, *GenerateWRequest) (*GenerateWResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedSlideServiceServer()
}

// UnimplementedSlideServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSlideServiceServer struct{}

func (UnimplementedSlideServiceServer) Solve(context.Context, *SolveGeetestCaptchaRequest) (*SolveGeetestCaptchaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedSlideServiceServer) GetCS(context.Context, *GetCSRequest) (*GetCSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCS not implemented")
}
func (UnimplementedSlideServiceServer) GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetType not implemented")
}
func (UnimplementedSlideServiceServer) GetNewCSArgs(context.Context, *GetNewCSArgsRequest) (*GetNewCSArgsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewCSArgs not implemented")
}
func (UnimplementedSlideServiceServer) CalculateKey(context.Context, *CalculateKeyRequest) (*CalculateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateKey not implemented")
}
func (UnimplementedSlideServiceServer) GenerateW(context.Context, *GenerateWRequest) (*GenerateWResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateW not implemented")
}
func (UnimplementedSlideServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedSlideServiceServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedSlideServiceServer) mustEmbedUnimplementedSlideServiceServer() {}
func (UnimplementedSlideServiceServer) testEmbeddedByValue()                      {}

// UnsafeSlideServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlideServiceServer will
// result in compilation errors.
type UnsafeSlideServiceServer interface {
	mustEmbedUnimplementedSlideServiceServer()
}

func RegisterSlideServiceServer(s grpc.ServiceRegistrar, srv SlideServiceServer) {
	// If the following call panics, it indicates UnimplementedSlideServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SlideService_ServiceDesc, srv)
}

func _SlideService_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveGeetestCaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlideServiceServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlideService_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlideServiceServer).Solve(ctx, req.(*SolveGeetestCaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlideService_GetCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlideServiceServer).GetCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlideService_GetCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlideServiceServer).GetCS(ctx, req.(*GetCSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlideService_GetType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlideServiceServer).GetType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlideService_GetType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlideServiceServer).GetType(ctx, req.(*GetTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlideService_GetNewCSArgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewCSArgsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlideServiceServer).GetNewCSArgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlideService_GetNewCSArgs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlideServiceServer).GetNewCSArgs(ctx, req.(*GetNewCSArgsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlideService_CalculateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlideServiceServer).CalculateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlideService_CalculateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlideServiceServer).CalculateKey(ctx, req.(*CalculateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlideService_GenerateW_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlideServiceServer).GenerateW(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlideService_GenerateW_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlideServiceServer).GenerateW(ctx, req.(*GenerateWRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlideService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlideServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlideService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlideServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlideService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlideServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlideService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlideServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SlideService_ServiceDesc is the grpc.ServiceDesc for SlideService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlideService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "captcha.SlideService",
	HandlerType: (*SlideServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _SlideService_Solve_Handler,
		},
		{
			MethodName: "GetCS",
			Handler:    _SlideService_GetCS_Handler,
		},
		{
			MethodName: "GetType",
			Handler:    _SlideService_GetType_Handler,
		},
		{
			MethodName: "GetNewCSArgs",
			Handler:    _SlideService_GetNewCSArgs_Handler,
		},
		{
			MethodName: "CalculateKey",
			Handler:    _SlideService_CalculateKey_Handler,
		},
		{
			MethodName: "GenerateW",
			Handler:    _SlideService_GenerateW_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _SlideService_Verify_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _SlideService_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "captcha.proto",
}
