"project_id": "906821"

"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true


files:
  - source: "/frontend/src/locales/zh-CN.json"
    translation: "/frontend/src/locales/%locale%.json"
  - source: "/internal/i18n/locales/active.zh-CN.json"
    translation: "/internal/i18n/locales/active.%locale%.json"
