// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BiliClient is the main Bilibili API client with device impersonation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as token$0 from "./token/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as githubutils$0 from "../githubutils/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../models/bili/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as _return$0 from "../models/bili/response/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../net/http/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as url$0 from "../../../net/url/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BindBWSTicket binds real-name identity to an electronic ticket.
 * 
 * Required before making reservations if the account hasn't bound yet
 * (the /reserve/info endpoint returns code 75638 when unbound).
 * 
 * Parameters:
 *   - bid: activity bid, e.g. 202501 for BWS 2025
 *   - idType: 0=身份证, 1=护照, 2=港澳通行证, 3=台湾通行证
 *   - personalID: the ID number
 *   - ticketNo: the 4-digit electronic ticket number
 *   - userName: the real name on the ID
 * 
 * Returns the API response code, message, and any transport/unmarshal error.
 * @param {number} bid
 * @param {number} idType
 * @param {string} personalID
 * @param {string} ticketNo
 * @param {string} userName
 * @returns {$CancellablePromise<[number, string]>}
 */
export function BindBWSTicket(bid, idType, personalID, ticketNo, userName) {
    return $Call.ByID(3696462855, bid, idType, personalID, ticketNo, userName);
}

/**
 * CheckAndUpdateCookie verifies login status, checks if a cookie refresh is needed,
 * and performs the refresh exchange using RSA-encrypted CSRF tokens.
 * Returns (refreshed, error).
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckAndUpdateCookie() {
    return $Call.ByID(4176834636);
}

/**
 * CheckForUpdate queries GitHub for the latest release and compares it with
 * the running build's commit hash. Returns an UpdateInfo struct serializable to JSON.
 * @returns {$CancellablePromise<githubutils$0.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(999416372).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateBuyer adds a new buyer for the current logged-in account.
 * Endpoint: POST https://show.bilibili.com/api/ticket/buyer/create
 * @param {string} name
 * @param {string} tel
 * @param {number} idType
 * @param {string} personalID
 * @param {boolean} isDefault
 * @returns {$CancellablePromise<void>}
 */
export function CreateBuyer(name, tel, idType, personalID, isDefault) {
    return $Call.ByID(697304653, name, tel, idType, personalID, isDefault);
}

/**
 * @returns {$CancellablePromise<$models.DeviceProfile>}
 */
export function ExportDeviceProfile() {
    return $Call.ByID(2863065395).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * FetchAvatar downloads the avatar image from the given URL (with Bilibili
 * Referer to bypass hotlink protection) and returns a base64 data URI.
 * Returns empty string if the fetch fails.
 * @param {string} faceURL
 * @returns {$CancellablePromise<string>}
 */
export function FetchAvatar(faceURL) {
    return $Call.ByID(3492814211, faceURL);
}

/**
 * FetchPluginList fetches the latest releases for all known plugins and returns
 * platform-specific download URLs.
 * @returns {$CancellablePromise<plugins$0.PluginListResult | null>}
 */
export function FetchPluginList() {
    return $Call.ByID(1710035849).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * FetchPluginListByName fetches releases for a single plugin by its name.
 * @param {string} name
 * @returns {$CancellablePromise<plugins$0.PluginListResult | null>}
 */
export function FetchPluginListByName(name) {
    return $Call.ByID(4154140283, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetAccountStatus returns the current login status and user info.
 * Calls Bilibili's nav endpoint. If logged in, returns name and UID.
 * @returns {$CancellablePromise<api$0.GetLoginInfoStruct | null>}
 */
export function GetAccountStatus() {
    return $Call.ByID(3235229807).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetAppVersion returns the current Bilibili app version info.
 * @returns {$CancellablePromise<api$0.BiliAppVersionStruct | null>}
 */
export function GetAppVersion() {
    return $Call.ByID(1154833923).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetAvailablePlugins returns the list of known plugin definitions.
 * @returns {$CancellablePromise<plugins$0.PluginDefinition[]>}
 */
export function GetAvailablePlugins() {
    return $Call.ByID(933601543).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetBUVID returns the current BUVID.
 * @returns {$CancellablePromise<string>}
 */
export function GetBUVID() {
    return $Call.ByID(2054817694);
}

/**
 * GetBWSMyReservations fetches the user's current BWS reservations.
 * @returns {$CancellablePromise<api$0.BWSMyReservationsStruct | null>}
 */
export function GetBWSMyReservations() {
    return $Call.ByID(3012833203).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetBWSReservationInfo fetches all reservation information for the given dates.
 * 
 * reserveDates is comma-separated, e.g. "20250711,20250712,20250713".
 * 
 * Returns a parsed BWSReservationData containing ticket mapping, activity
 * mapping, and already-reserved activity IDs for convenient access.
 * @param {string} reserveDates
 * @returns {$CancellablePromise<_return$0.BWSReservationData | null>}
 */
export function GetBWSReservationInfo(reserveDates) {
    return $Call.ByID(2771097504, reserveDates).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetBrowserUA() {
    return $Call.ByID(2416573376);
}

/**
 * GetClockOffset returns the current calibrated clock offset.
 * @returns {$CancellablePromise<time$0.Duration>}
 */
export function GetClockOffset() {
    return $Call.ByID(2090534207);
}

/**
 * GetConfirmInformation fetches order confirmation info including buyer list,
 * total price, ticket info, etc. Required before placing an order for real-name projects.
 * @param {_return$0.RequestTokenAndPToken | null} tokens
 * @param {string} projectID
 * @returns {$CancellablePromise<api$0.ConfirmStruct | null>}
 */
export function GetConfirmInformation(tokens, projectID) {
    return $Call.ByID(3975148404, tokens, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetCookieJar returns the underlying cookie jar.
 * @returns {$CancellablePromise<http$0.CookieJar>}
 */
export function GetCookieJar() {
    return $Call.ByID(2522180389);
}

/**
 * GetFingerprint returns the current device fingerprint.
 * @returns {$CancellablePromise<$models.Fingerprint>}
 */
export function GetFingerprint() {
    return $Call.ByID(1128796930).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetInfocUUID returns the current infoc UUID.
 * @returns {$CancellablePromise<string>}
 */
export function GetInfocUUID() {
    return $Call.ByID(4280086544);
}

/**
 * @param {string} projectID
 * @param {string} token
 * @param {number} orderID
 * @returns {$CancellablePromise<api$0.OrderStatusStruct | null>}
 */
export function GetOrderStatus(projectID, token, orderID) {
    return $Call.ByID(3441300396, projectID, token, orderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetProjectInformation fetches project info from the ticket mall.
 * Returns project name, sale time range, hot/real-name flags, etc.
 * @param {string} projectID
 * @returns {$CancellablePromise<_return$0.ProjectInformation | null>}
 */
export function GetProjectInformation(projectID) {
    return $Call.ByID(3859471199, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {string} projectID
 * @returns {$CancellablePromise<_return$0.ProjectInformation | null>}
 */
export function GetProjectInformationNew(projectID) {
    return $Call.ByID(1884875839, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * GetQRCodeUrlAndKey fetches a QR code URL and key for Bilibili login.
 * Returns the QR code image URL and the poll key for status checking.
 * @returns {$CancellablePromise<api$0.QRLoginKeyStruct | null>}
 */
export function GetQRCodeUrlAndKey() {
    return $Call.ByID(4275140849).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetQRLoginState polls the QR code login status.
 * qrcodeKey is the key returned by GetQRCodeUrlAndKey.
 * Returns Code=0 and RefreshToken when scan is confirmed, other codes otherwise.
 * @param {string} qrcodeKey
 * @returns {$CancellablePromise<api$0.VerifyQRLoginStateStruct | null>}
 */
export function GetQRLoginState(qrcodeKey) {
    return $Call.ByID(3303696915, qrcodeKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * GetRealnameBuyerList fetches the list of buyers for a real-name project, which includes sensitive info like ID numbers.
 * Parameters: none
 * 
 * Returns: error and list of buyers with non-sensitive info (ID number is not included)
 * @returns {$CancellablePromise<api$0.BuyerNoSensitiveStruct[]>}
 */
export function GetRealnameBuyerList() {
    return $Call.ByID(3757675028).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetRealnameBuyerListNew fetches the list of buyers for a real-name project
 * using the new buyerinfo/list API format, which returns the list directly
 * (not wrapped in vo) along with max_limit and isDynamic fields, and includes
 * additional buyer fields (def, cardImgFront, cardImgBack, etc.).
 * 
 * The new API response is mapped back to the original BuyerNoSensitiveStruct
 * so callers can use the same struct as before.
 * 
 * Parameters: none
 * 
 * Returns: error and list of buyers with non-sensitive info
 * @returns {$CancellablePromise<api$0.BuyerNoSensitiveStruct[]>}
 */
export function GetRealnameBuyerListNew() {
    return $Call.ByID(194458130).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetRefreshToken returns the stored refresh_token.
 * @returns {$CancellablePromise<string>}
 */
export function GetRefreshToken() {
    return $Call.ByID(1871062998);
}

/**
 * GetRequestTokenAndPToken fetches the request token and ptoken needed for order preparation.
 * 
 * For hot projects, a CToken (window-stats-based token) is generated and included
 * in the prepare request. count is the number of tickets to purchase.
 * @param {token$0.Generator} tokenGen
 * @param {string} projectID
 * @param {_return$0.TicketSkuScreenID} ticket
 * @param {number} count
 * @returns {$CancellablePromise<_return$0.RequestTokenAndPToken | null>}
 */
export function GetRequestTokenAndPToken(tokenGen, projectID, ticket, count) {
    return $Call.ByID(3016133420, tokenGen, projectID, ticket, count).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * GetTargetBuyerSensitiveData fetches the sensitive data of a buyer for a real-name project.
 * Parameters: int buyerID
 * 
 * Returns: error and buyer struct with sensitive data (ID number, phone number, etc.)
 * @param {number} buyerID
 * @returns {$CancellablePromise<api$0.BuyerStruct>}
 */
export function GetTargetBuyerSensitiveData(buyerID) {
    return $Call.ByID(1394194950, buyerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetTicketSkuIDsByProjectID returns all ticket SKU/screen pairs for a project.
 * @param {string} projectID
 * @returns {$CancellablePromise<_return$0.TicketSkuScreenID[]>}
 */
export function GetTicketSkuIDsByProjectID(projectID) {
    return $Call.ByID(3209631470, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetTicketSkuIDsByProjectIDNew returns all ticket SKU/screen pairs for a project
 * using the mall-search-items/items_detail/info API (floor-based layout).
 * @param {string} projectID
 * @returns {$CancellablePromise<_return$0.TicketSkuScreenID[]>}
 */
export function GetTicketSkuIDsByProjectIDNew(projectID) {
    return $Call.ByID(3000739576, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * HasCaptchaSolver returns whether a captcha solver has been installed.
 * @returns {$CancellablePromise<boolean>}
 */
export function HasCaptchaSolver() {
    return $Call.ByID(2045162511);
}

/**
 * IsDebug returns whether debug mode is enabled.
 * Both frontend and backend use this to control verbose logging.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDebug() {
    return $Call.ByID(961172373);
}

/**
 * MakeBWSReservation submits a reservation request for a specific activity.
 * 
 * Parameters:
 *   - ticketNo: the electronic ticket number for the corresponding date
 *   - reservationID: the activity's reserve_id
 * 
 * Returns the API response code, message (even when code != 0), and a Go error
 * only for transport/unmarshal failures.
 * @param {string} ticketNo
 * @param {number} reservationID
 * @returns {$CancellablePromise<[number, string]>}
 */
export function MakeBWSReservation(ticketNo, reservationID) {
    return $Call.ByID(1930975938, ticketNo, reservationID);
}

/**
 * PersistCookies triggers an immediate save of all cookies to persistent storage.
 * It must be called after SetCookieSaveCallback has been called.
 * @returns {$CancellablePromise<void>}
 */
export function PersistCookies() {
    return $Call.ByID(4252256949);
}

/**
 * SetCaptchaSolver installs a captcha solving function. When set, voucher
 * errors (x-bili-gaia-vvoucher) are resolved automatically inside
 * WrapRoundTripFunc instead of being returned as errors.
 * @param {$models.CaptchaSolverFn} solver
 * @returns {$CancellablePromise<void>}
 */
export function SetCaptchaSolver(solver) {
    return $Call.ByID(3828844983, solver);
}

/**
 * SetClockOffset stores a calibrated clock offset for use in request timestamps.
 * offset = server_time − local_time. Positive means local is behind.
 * @param {time$0.Duration} offset
 * @returns {$CancellablePromise<void>}
 */
export function SetClockOffset(offset) {
    return $Call.ByID(4116690699, offset);
}

/**
 * SetCookieSaveCallback sets a callback that is invoked whenever PersistCookies is called.
 * The callback should dump all cookies from the jar and write them to persistent storage.
 * @param {any} cb
 * @returns {$CancellablePromise<void>}
 */
export function SetCookieSaveCallback(cb) {
    return $Call.ByID(920164570, cb);
}

/**
 * SetRefreshToken stores the Bilibili refresh_token for cookie refresh operations.
 * Call this after QR login succeeds (the token is in the QR login response).
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function SetRefreshToken(token) {
    return $Call.ByID(4271901914, token);
}

/**
 * SignAppParams signs a parameter map using Bilibili's Android APP signature algorithm.
 * 
 * It adds appkey and ts parameters, then computes sign = MD5(sorted_params + appSec).
 * Used for endpoints requiring APP-level authentication.
 * @param {{ [_ in string]?: any }} params
 * @returns {$CancellablePromise<url$0.Values>}
 */
export function SignAppParams(params) {
    return $Call.ByID(217165588, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * SignWithWbi signs URL query parameters using Bilibili's WBI algorithm.
 * 
 * It adds w_rid (MD5(query + mixin_key)) and wts (current Unix timestamp)
 * parameters to the URL. If the WBI key is expired or forceUpdate is true,
 * a new key is fetched automatically.
 * @param {boolean} forceUpdate
 * @param {url$0.URL | null} targetURL
 * @returns {$CancellablePromise<void>}
 */
export function SignWithWbi(forceUpdate, targetURL) {
    return $Call.ByID(770108153, forceUpdate, targetURL);
}

/**
 * SubmitOrder sends the final order creation request to Bilibili's ticket mall.
 * 
 * Parameters:
 *   - ctx: context for cancellation
 *   - tokenGen: token generation strategy (CToken for hot projects, Normal otherwise)
 *   - whenGenPToken: timestamp when the ptoken was generated, sent as timestamp field
 *   - tokens: the RequestToken/PToken/GaiaToken from GetRequestTokenAndPToken
 *   - projectID: the project ID string
 *   - ticket: the target ticket SKU/screen
 *   - buyer: buyer info — map[string]string for Ordinary, []map[string]any for ForceRealName
 *   - buyerType: Ordinary or ForceRealName
 * 
 * Returns: error, API response code, API message, and the order result struct.
 * @param {token$0.Generator} tokenGen
 * @param {time$0.Time} whenGenPToken
 * @param {_return$0.RequestTokenAndPToken | null} tokens
 * @param {string} projectID
 * @param {_return$0.TicketSkuScreenID} ticket
 * @param {_return$0.TicketBuyer[]} buyers
 * @param {api$0.ConfirmStruct | null} confirmInfo
 * @returns {$CancellablePromise<[number, string, api$0.TicketOrderStruct]>}
 */
export function SubmitOrder(tokenGen, whenGenPToken, tokens, projectID, ticket, buyers, confirmInfo) {
    return $Call.ByID(2094968198, tokenGen, whenGenPToken, tokens, projectID, ticket, buyers, confirmInfo).then(/** @type {($result: any) => any} */(($result) => {
        $result[2] = $$createType36($result[2]);
        return $result;
    }));
}

/**
 * TryToRefreshNewBiliTicket checks the bili_ticket cookie and refreshes it if
 * it will expire within 1 hour. The bili_ticket is required for API access.
 * Returns (refreshed, error).
 * @returns {$CancellablePromise<boolean>}
 */
export function TryToRefreshNewBiliTicket() {
    return $Call.ByID(3626551691);
}

// Private type creation functions
const $$createType0 = githubutils$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DeviceProfile.createFrom;
const $$createType3 = plugins$0.PluginListResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = api$0.GetLoginInfoStruct.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = api$0.BiliAppVersionStruct.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = plugins$0.PluginDefinition.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = api$0.BWSMyReservationsStruct.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = _return$0.BWSReservationData.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = api$0.ConfirmStruct.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $models.Fingerprint.createFrom;
const $$createType18 = api$0.OrderStatusStruct.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = _return$0.ProjectInformation.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = api$0.QRLoginKeyStruct.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = api$0.VerifyQRLoginStateStruct.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = api$0.BuyerNoSensitiveStruct.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = _return$0.RequestTokenAndPToken.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = api$0.BuyerStruct.createFrom;
const $$createType31 = _return$0.TicketSkuScreenID.createFrom;
const $$createType32 = $Create.Array($$createType31);
var $$createType33 = /** @type {(...args: any[]) => any} */(function $$initCreateType33(...args) {
    if ($$createType33 === $$initCreateType33) {
        $$createType33 = $$createType35;
    }
    return $$createType33(...args);
});
const $$createType34 = $Create.Array($Create.Any);
const $$createType35 = $Create.Map($Create.Any, $$createType34);
const $$createType36 = api$0.TicketOrderStruct.createFrom;
