// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BiliClient from "./biliclient.js";
export {
    BiliClient
};

export {
    BiliClient,
    DeviceProfile,
    Fingerprint
} from "./models.js";

import * as $models from "./models.js";

/**
 * CaptchaSolverFn is a function that solves a geetest captcha given gt+challenge.
 * It returns the validate string on success.
 * @typedef {$models.CaptchaSolverFn} CaptchaSolverFn
 */
