// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BiliClient is the main Bilibili API client with device impersonation.
 */
export class BiliClient {
    /**
     * Creates a new BiliClient instance.
     * @param {Partial<BiliClient>} [$$source = {}] - The source object to create the BiliClient.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BiliClient instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BiliClient}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BiliClient(/** @type {Partial<BiliClient>} */($$parsedSource));
    }
}

/**
 * CaptchaSolverFn is a function that solves a geetest captcha given gt+challenge.
 * It returns the validate string on success.
 * @typedef {any} CaptchaSolverFn
 */

export class DeviceProfile {
    /**
     * Creates a new DeviceProfile instance.
     * @param {Partial<DeviceProfile>} [$$source = {}] - The source object to create the DeviceProfile.
     */
    constructor($$source = {}) {
        if (!("buvid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buvid"] = "";
        }
        if (!("infocUuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["infocUuid"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {Fingerprint}
             */
            this["fingerprint"] = (new Fingerprint());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceProfile}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fingerprint" in $$parsedSource) {
            $$parsedSource["fingerprint"] = $$createField2_0($$parsedSource["fingerprint"]);
        }
        return new DeviceProfile(/** @type {Partial<DeviceProfile>} */($$parsedSource));
    }
}

/**
 * Fingerprint holds device fingerprint data for anti-detection.
 */
export class Fingerprint {
    /**
     * Creates a new Fingerprint instance.
     * @param {Partial<Fingerprint>} [$$source = {}] - The source object to create the Fingerprint.
     */
    constructor($$source = {}) {
        if (!("BuvidLocal" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["BuvidLocal"] = "";
        }
        if (!("Buvidfp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Buvidfp"] = "";
        }
        if (!("Webglfp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Webglfp"] = "";
        }
        if (!("Canvasfp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Canvasfp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fingerprint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Fingerprint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fingerprint(/** @type {Partial<Fingerprint>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Fingerprint.createFrom;
