// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is exposed as a Wails v3 service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as biliutils$0 from "../../lib/biliutils/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBiliClient returns the underlying BiliClient.
 * @returns {$CancellablePromise<biliutils$0.BiliClient | null>}
 */
export function GetBiliClient() {
    return $Call.ByID(1580951322).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLocale returns the current application locale.
 * Returns empty string if no locale has been set (first startup).
 * @returns {$CancellablePromise<string>}
 */
export function GetLocale() {
    return $Call.ByID(1382829361);
}

/**
 * IsVerified checks whether the anti-scalper declaration has been accepted.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsVerified() {
    return $Call.ByID(2902628909);
}

/**
 * OpenPayQRWindow opens a compact QR-code payment window.
 * @param {$models.PayQRWindowOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OpenPayQRWindow(options) {
    return $Call.ByID(2297851886, options);
}

/**
 * OpenQRTestWindow creates a new window with a test QR code.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function OpenQRTestWindow(text) {
    return $Call.ByID(2406902978, text);
}

/**
 * SetApp stores the Wails v3 application reference for window management.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(4256893662, app);
}

/**
 * SetLocale sets the application locale and persists it.
 * @param {string} locale
 * @returns {$CancellablePromise<void>}
 */
export function SetLocale(locale) {
    return $Call.ByID(2991417501, locale);
}

/**
 * Verify accepts the anti-scalper declaration. Returns true if the input
 * matches the required phrase and persistence succeeds.
 * @param {string} input
 * @returns {$CancellablePromise<boolean>}
 */
export function Verify(input) {
    return $Call.ByID(2109125804, input);
}

// Private type creation functions
const $$createType0 = biliutils$0.BiliClient.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
