// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../cluster/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worker$0 from "../../cluster/worker/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as biliutils$0 from "../../lib/biliutils/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} document
 * @returns {$CancellablePromise<void>}
 */
export function AddWorker(document) {
    return $Call.ByID(906604416, document);
}

/**
 * AddWorkerFromEncodedConfig decodes a Base4096-encoded worker configuration
 * and adds the worker to the repository.  The encoded string carries both
 * the worker-side and employer-side TLS material, so no prior TLS setup
 * is required — it is extracted directly from the config.
 * 
 * overrideAddress, when non-empty, overrides the dial address (rc.Listen)
 * embedded in the encoded config.  This allows the employer to specify the
 * real reachable IP:port of the worker, which may differ from the listen
 * address the worker was configured with (e.g. 0.0.0.0:18080 vs the actual
 * public IP).
 * @param {string} encodedConfig
 * @param {string} overrideAddress
 * @returns {$CancellablePromise<void>}
 */
export function AddWorkerFromEncodedConfig(encodedConfig, overrideAddress) {
    return $Call.ByID(428282756, encodedConfig, overrideAddress);
}

/**
 * @param {string} attemptID
 * @returns {$CancellablePromise<worker$0.LogEntry[]>}
 */
export function AttemptLogs(attemptID) {
    return $Call.ByID(1421701051, attemptID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} name
 * @param {domain$0.ResourceRole} role
 * @returns {$CancellablePromise<$models.AccountLoginStart>}
 */
export function BeginAccountLogin(name, role) {
    return $Call.ByID(1955744192, name, role).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(2258203665);
}

/**
 * @param {string} accountID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAccount(accountID) {
    return $Call.ByID(156685383, accountID);
}

/**
 * @param {string} macroID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMacro(macroID) {
    return $Call.ByID(4131930620, macroID);
}

/**
 * @param {string} macroID
 * @param {string} purchaseGroupID
 * @returns {$CancellablePromise<void>}
 */
export function DeletePurchaseGroup(macroID, purchaseGroupID) {
    return $Call.ByID(1243568346, macroID, purchaseGroupID);
}

/**
 * @param {string} workerID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorker(workerID) {
    return $Call.ByID(3994936854, workerID);
}

/**
 * DisconnectWorker closes the gRPC connection to a worker (keeping the TLS
 * config so it can be reconnected later).
 * @param {string} workerID
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectWorker(workerID) {
    return $Call.ByID(4179362203, workerID);
}

/**
 * GenerateRemoteWorkerConfig creates TLS material and a complete configuration
 * for a remote worker, then encodes it as a Base4096 string for copy-paste
 * distribution.  Only the employer-side TLS credentials are stored so that
 * mTLS works once the worker comes online; the worker is **not** added to
 * the repository list (the user must add it manually via AddWorker after
 * the worker is deployed).
 * 
 * Parameters:
 *   - workerID: unique identifier for the worker (e.g. "home-server")
 *   - listen: address the worker will listen on (e.g. "0.0.0.0:18080")
 *   - hosts: comma-separated list of DNS names / IPs for the server TLS cert
 *     (e.g. "myworker.example.com,192.168.1.100")
 * @param {string} workerID
 * @param {string} listen
 * @param {string} hosts
 * @returns {$CancellablePromise<$models.GenerateRemoteWorkerConfigResponse>}
 */
export function GenerateRemoteWorkerConfig(workerID, listen, hosts) {
    return $Call.ByID(65451882, workerID, listen, hosts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetWorkerConfig reads the full connection settings for a worker (node info
 * plus TLS PEM material) so that the frontend can pre-fill the edit form.
 * @param {string} workerID
 * @returns {$CancellablePromise<$models.WorkerConfigResponse>}
 */
export function GetWorkerConfig(workerID) {
    return $Call.ByID(804367285, workerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} document
 * @returns {$CancellablePromise<void>}
 */
export function ImportAccount(document) {
    return $Call.ByID(2969653501, document);
}

/**
 * @param {number} projectID
 * @param {number} screenID
 * @param {number} skuID
 * @returns {$CancellablePromise<$models.SKUInspection>}
 */
export function InspectSKU(projectID, screenID, skuID) {
    return $Call.ByID(838277146, projectID, screenID, skuID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.ProjectCatalog>}
 */
export function LoadProject(projectID) {
    return $Call.ByID(1638604888, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.AccountLoginPoll>}
 */
export function PollAccountLogin(sessionID) {
    return $Call.ByID(2914391778, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} document
 * @param {boolean} confirmed
 * @returns {$CancellablePromise<void>}
 */
export function ProvisionBuyer(document, confirmed) {
    return $Call.ByID(1125737957, document, confirmed);
}

/**
 * ReconnectWorker re-establishes the gRPC connection to a worker and verifies
 * it with a health check.  Retries up to 5 times with 5s intervals.
 * @param {string} workerID
 * @returns {$CancellablePromise<void>}
 */
export function ReconnectWorker(workerID) {
    return $Call.ByID(1440299734, workerID);
}

/**
 * @param {string} document
 * @returns {$CancellablePromise<void>}
 */
export function SaveMacro(document) {
    return $Call.ByID(1953980394, document);
}

/**
 * @param {string} document
 * @returns {$CancellablePromise<void>}
 */
export function SavePurchaseGroup(document) {
    return $Call.ByID(869091684, document);
}

/**
 * @param {string} document
 * @returns {$CancellablePromise<void>}
 */
export function SaveTaskGroup(document) {
    return $Call.ByID(3889808242, document);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(2344104616, app);
}

/**
 * @param {biliutils$0.BiliClient | null} client
 * @returns {$CancellablePromise<void>}
 */
export function SetCatalogClient(client) {
    return $Call.ByID(3998464803, client);
}

/**
 * @param {any} notify
 * @returns {$CancellablePromise<void>}
 */
export function SetNotifier(notify) {
    return $Call.ByID(592666951, notify);
}

/**
 * @returns {$CancellablePromise<$models.ClusterSnapshot>}
 */
export function Snapshot() {
    return $Call.ByID(359805947).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2864448489);
}

/**
 * @param {string} macroID
 * @returns {$CancellablePromise<void>}
 */
export function StartMacro(macroID) {
    return $Call.ByID(1731728319, macroID);
}

/**
 * StopAttempt stops a running attempt by telling its worker to cancel it.
 * @param {string} attemptID
 * @returns {$CancellablePromise<void>}
 */
export function StopAttempt(attemptID) {
    return $Call.ByID(1586642832, attemptID);
}

/**
 * StopMacro stops all active attempts belonging to a macro and disarms its intents.
 * @param {string} macroID
 * @returns {$CancellablePromise<void>}
 */
export function StopMacro(macroID) {
    return $Call.ByID(3190974905, macroID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SwitchToReflow() {
    return $Call.ByID(131923175);
}

/**
 * @param {string} accountID
 * @returns {$CancellablePromise<domain$0.Buyer[]>}
 */
export function SyncAccountBuyers(accountID) {
    return $Call.ByID(1255009067, accountID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * SyncAllAccountBuyers syncs buyers from every enabled account and ensures
 * the logical_buyers table retains the most complete (unmasked) real-name
 * information. The same real person on multiple accounts is matched and
 * deduplicated into a single logical buyer entry.
 * @returns {$CancellablePromise<domain$0.Buyer[]>}
 */
export function SyncAllAccountBuyers() {
    return $Call.ByID(45300210).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * SyncBuyerToAccount provisions a logical buyer onto a target Bilibili
 * account. If the buyer already exists on that account's real-name list the
 * call is a no-op; otherwise a new buyer is created on the remote account.
 * @param {string} logicalBuyerID
 * @param {string} targetAccountID
 * @returns {$CancellablePromise<void>}
 */
export function SyncBuyerToAccount(logicalBuyerID, targetAccountID) {
    return $Call.ByID(1960269033, logicalBuyerID, targetAccountID);
}

/**
 * SyncBuyerToAllAccounts provisions a logical buyer onto every enabled
 * Bilibili account that does not already have it. Accounts that already
 * contain the buyer are skipped without any remote calls.
 * @param {string} logicalBuyerID
 * @returns {$CancellablePromise<void>}
 */
export function SyncBuyerToAllAccounts(logicalBuyerID) {
    return $Call.ByID(2793069357, logicalBuyerID);
}

/**
 * SyncMainAccount mirrors the credentials used by the employer UI into the
 * account pool. The UID-derived ID makes this converge with an independently
 * scanned pool account instead of creating a duplicate.
 * @returns {$CancellablePromise<void>}
 */
export function SyncMainAccount() {
    return $Call.ByID(3843985720);
}

/**
 * UpdateWorker updates the connection settings (address, TLS, role) for an
 * existing worker. The worker must not have active attempts. Accepts the
 * same JSON document shape as AddWorker.
 * @param {string} document
 * @returns {$CancellablePromise<void>}
 */
export function UpdateWorker(document) {
    return $Call.ByID(4079307172, document);
}

// Private type creation functions
const $$createType0 = worker$0.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.AccountLoginStart.createFrom;
const $$createType3 = $models.GenerateRemoteWorkerConfigResponse.createFrom;
const $$createType4 = $models.WorkerConfigResponse.createFrom;
const $$createType5 = $models.SKUInspection.createFrom;
const $$createType6 = $models.ProjectCatalog.createFrom;
const $$createType7 = $models.AccountLoginPoll.createFrom;
const $$createType8 = $models.ClusterSnapshot.createFrom;
const $$createType9 = domain$0.Buyer.createFrom;
const $$createType10 = $Create.Array($$createType9);
