// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../cluster/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class AccountLoginPoll {
    /**
     * Creates a new AccountLoginPoll instance.
     * @param {Partial<AccountLoginPoll>} [$$source = {}] - The source object to create the AccountLoginPoll.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["code"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["accountId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountLoginPoll instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountLoginPoll}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountLoginPoll(/** @type {Partial<AccountLoginPoll>} */($$parsedSource));
    }
}

export class AccountLoginStart {
    /**
     * Creates a new AccountLoginStart instance.
     * @param {Partial<AccountLoginStart>} [$$source = {}] - The source object to create the AccountLoginStart.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountLoginStart instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountLoginStart}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountLoginStart(/** @type {Partial<AccountLoginStart>} */($$parsedSource));
    }
}

export class AccountSummary {
    /**
     * Creates a new AccountSummary instance.
     * @param {Partial<AccountSummary>} [$$source = {}] - The source object to create the AccountSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {domain$0.ResourceRole}
             */
            this["role"] = domain$0.ResourceRole.$zero;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["cooldownUntil"] = undefined;
        }
        if (!("credentialVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["credentialVersion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountSummary(/** @type {Partial<AccountSummary>} */($$parsedSource));
    }
}

export class AttemptSummary {
    /**
     * Creates a new AttemptSummary instance.
     * @param {Partial<AttemptSummary>} [$$source = {}] - The source object to create the AttemptSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("intentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["intentId"] = "";
        }
        if (!("accountId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accountId"] = "";
        }
        if (!("workerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workerId"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.AttemptState}
             */
            this["state"] = domain$0.AttemptState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["orderId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["paymentUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.FailureReason | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttemptSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AttemptSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttemptSummary(/** @type {Partial<AttemptSummary>} */($$parsedSource));
    }
}

/**
 * BuyerAccountBadge represents an account that owns a particular buyer.
 */
export class BuyerAccountBadge {
    /**
     * Creates a new BuyerAccountBadge instance.
     * @param {Partial<BuyerAccountBadge>} [$$source = {}] - The source object to create the BuyerAccountBadge.
     */
    constructor($$source = {}) {
        if (!("accountId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accountId"] = "";
        }
        if (!("accountName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accountName"] = "";
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuyerAccountBadge instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuyerAccountBadge}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuyerAccountBadge(/** @type {Partial<BuyerAccountBadge>} */($$parsedSource));
    }
}

/**
 * BuyerWithAccounts extends domain.Buyer with the list of accounts that
 * have this buyer in their real-name list.
 */
export class BuyerWithAccounts {
    /**
     * Creates a new BuyerWithAccounts instance.
     * @param {Partial<BuyerWithAccounts>} [$$source = {}] - The source object to create the BuyerWithAccounts.
     */
    constructor($$source = {}) {
        if (!("logicalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logicalId"] = "";
        }
        if (!("buyerId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["buyerId"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["idCard"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["type"] = 0;
        }
        if (!("accounts" in $$source)) {
            /**
             * @member
             * @type {BuyerAccountBadge[]}
             */
            this["accounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuyerWithAccounts instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuyerWithAccounts}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField6_0($$parsedSource["accounts"]);
        }
        return new BuyerWithAccounts(/** @type {Partial<BuyerWithAccounts>} */($$parsedSource));
    }
}

export class CatalogSKU {
    /**
     * Creates a new CatalogSKU instance.
     * @param {Partial<CatalogSKU>} [$$source = {}] - The source object to create the CatalogSKU.
     */
    constructor($$source = {}) {
        if (!("screenId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["screenId"] = 0;
        }
        if (!("skuId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skuId"] = 0;
        }
        if (!("screenName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenName"] = "";
        }
        if (!("skuName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skuName"] = "";
        }
        if (!("price" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["price"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("eventTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["eventTime"] = null;
        }
        if (!("saleStart" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["saleStart"] = null;
        }
        if (!("saleEnd" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["saleEnd"] = null;
        }
        if (!("orderCapacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["orderCapacity"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogSKU instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CatalogSKU}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogSKU(/** @type {Partial<CatalogSKU>} */($$parsedSource));
    }
}

export class ClusterSnapshot {
    /**
     * Creates a new ClusterSnapshot instance.
     * @param {Partial<ClusterSnapshot>} [$$source = {}] - The source object to create the ClusterSnapshot.
     */
    constructor($$source = {}) {
        if (!("taskGroups" in $$source)) {
            /**
             * @member
             * @type {domain$0.TaskGroup[]}
             */
            this["taskGroups"] = [];
        }
        if (!("accounts" in $$source)) {
            /**
             * @member
             * @type {AccountSummary[]}
             */
            this["accounts"] = [];
        }
        if (!("buyers" in $$source)) {
            /**
             * @member
             * @type {BuyerWithAccounts[]}
             */
            this["buyers"] = [];
        }
        if (!("workers" in $$source)) {
            /**
             * @member
             * @type {WorkerSummary[]}
             */
            this["workers"] = [];
        }
        if (!("macros" in $$source)) {
            /**
             * @member
             * @type {MacroSummary[]}
             */
            this["macros"] = [];
        }
        if (!("attempts" in $$source)) {
            /**
             * @member
             * @type {AttemptSummary[]}
             */
            this["attempts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClusterSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType11;
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("taskGroups" in $$parsedSource) {
            $$parsedSource["taskGroups"] = $$createField0_0($$parsedSource["taskGroups"]);
        }
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField1_0($$parsedSource["accounts"]);
        }
        if ("buyers" in $$parsedSource) {
            $$parsedSource["buyers"] = $$createField2_0($$parsedSource["buyers"]);
        }
        if ("workers" in $$parsedSource) {
            $$parsedSource["workers"] = $$createField3_0($$parsedSource["workers"]);
        }
        if ("macros" in $$parsedSource) {
            $$parsedSource["macros"] = $$createField4_0($$parsedSource["macros"]);
        }
        if ("attempts" in $$parsedSource) {
            $$parsedSource["attempts"] = $$createField5_0($$parsedSource["attempts"]);
        }
        return new ClusterSnapshot(/** @type {Partial<ClusterSnapshot>} */($$parsedSource));
    }
}

/**
 * GenerateRemoteWorkerConfigResponse is returned by GenerateRemoteWorkerConfig.
 */
export class GenerateRemoteWorkerConfigResponse {
    /**
     * Creates a new GenerateRemoteWorkerConfigResponse instance.
     * @param {Partial<GenerateRemoteWorkerConfigResponse>} [$$source = {}] - The source object to create the GenerateRemoteWorkerConfigResponse.
     */
    constructor($$source = {}) {
        if (!("encodedConfig" in $$source)) {
            /**
             * Base4096 string for the worker
             * @member
             * @type {string}
             */
            this["encodedConfig"] = "";
        }
        if (!("workerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workerId"] = "";
        }
        if (!("listen" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["listen"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateRemoteWorkerConfigResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GenerateRemoteWorkerConfigResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateRemoteWorkerConfigResponse(/** @type {Partial<GenerateRemoteWorkerConfigResponse>} */($$parsedSource));
    }
}

export class MacroSummary {
    /**
     * Creates a new MacroSummary instance.
     * @param {Partial<MacroSummary>} [$$source = {}] - The source object to create the MacroSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("taskGroupId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskGroupId"] = "";
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["projectName"] = undefined;
        }
        if (!("screenId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["screenId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["screenName"] = undefined;
        }
        if (!("skuId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skuId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skuName"] = undefined;
        }
        if (!("eventDay" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventDay"] = "";
        }
        if (!("eventDayConfirmed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["eventDayConfirmed"] = false;
        }
        if (!("needsReview" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsReview"] = false;
        }
        if (!("smartMerge" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["smartMerge"] = false;
        }
        if (!("orderCapacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["orderCapacity"] = 0;
        }
        if (!("capacitySource" in $$source)) {
            /**
             * @member
             * @type {domain$0.CapacitySource}
             */
            this["capacitySource"] = domain$0.CapacitySource.$zero;
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("desiredReplicas" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["desiredReplicas"] = 0;
        }
        if (!("hardConcurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hardConcurrency"] = 0;
        }
        if (!("startAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startAt"] = null;
        }
        if (!("deadline" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["deadline"] = null;
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {domain$0.Phase}
             */
            this["phase"] = domain$0.Phase.$zero;
        }
        if (!("purchaseGroups" in $$source)) {
            /**
             * @member
             * @type {domain$0.PurchaseGroup[]}
             */
            this["purchaseGroups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacroSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacroSummary}
     */
    static createFrom($$source = {}) {
        const $$createField20_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("purchaseGroups" in $$parsedSource) {
            $$parsedSource["purchaseGroups"] = $$createField20_0($$parsedSource["purchaseGroups"]);
        }
        return new MacroSummary(/** @type {Partial<MacroSummary>} */($$parsedSource));
    }
}

export class PayQRWindowOptions {
    /**
     * Creates a new PayQRWindowOptions instance.
     * @param {Partial<PayQRWindowOptions>} [$$source = {}] - The source object to create the PayQRWindowOptions.
     */
    constructor($$source = {}) {
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["project"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["screen"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sku"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["buyer"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["expire"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["orderTime"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PayQRWindowOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PayQRWindowOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PayQRWindowOptions(/** @type {Partial<PayQRWindowOptions>} */($$parsedSource));
    }
}

export class ProjectCatalog {
    /**
     * Creates a new ProjectCatalog instance.
     * @param {Partial<ProjectCatalog>} [$$source = {}] - The source object to create the ProjectCatalog.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("forceRealName" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["forceRealName"] = false;
        }
        if (!("idBind" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["idBind"] = 0;
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["start"] = null;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["end"] = null;
        }
        if (!("tickets" in $$source)) {
            /**
             * @member
             * @type {CatalogSKU[]}
             */
            this["tickets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectCatalog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectCatalog}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tickets" in $$parsedSource) {
            $$parsedSource["tickets"] = $$createField6_0($$parsedSource["tickets"]);
        }
        return new ProjectCatalog(/** @type {Partial<ProjectCatalog>} */($$parsedSource));
    }
}

export class SKUInspection {
    /**
     * Creates a new SKUInspection instance.
     * @param {Partial<SKUInspection>} [$$source = {}] - The source object to create the SKUInspection.
     */
    constructor($$source = {}) {
        if (!("eventDay" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventDay"] = "";
        }
        if (!("orderCapacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["orderCapacity"] = 0;
        }
        if (!("capacitySource" in $$source)) {
            /**
             * @member
             * @type {domain$0.CapacitySource}
             */
            this["capacitySource"] = domain$0.CapacitySource.$zero;
        }
        if (!("saleStart" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["saleStart"] = null;
        }
        if (!("saleEnd" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["saleEnd"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SKUInspection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SKUInspection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SKUInspection(/** @type {Partial<SKUInspection>} */($$parsedSource));
    }
}

/**
 * WorkerConfigResponse returns the full configuration for a worker, suitable
 * for pre-filling an edit form.
 */
export class WorkerConfigResponse {
    /**
     * Creates a new WorkerConfigResponse instance.
     * @param {Partial<WorkerConfigResponse>} [$$source = {}] - The source object to create the WorkerConfigResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {domain$0.ResourceRole}
             */
            this["role"] = domain$0.ResourceRole.$zero;
        }
        if (!("caCert" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["caCert"] = "";
        }
        if (!("clientCert" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientCert"] = "";
        }
        if (!("clientKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientKey"] = "";
        }
        if (!("tlsServerName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tlsServerName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkerConfigResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkerConfigResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkerConfigResponse(/** @type {Partial<WorkerConfigResponse>} */($$parsedSource));
    }
}

export class WorkerSummary {
    /**
     * Creates a new WorkerSummary instance.
     * @param {Partial<WorkerSummary>} [$$source = {}] - The source object to create the WorkerSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {domain$0.ResourceRole}
             */
            this["role"] = domain$0.ResourceRole.$zero;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("healthy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["healthy"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["activeAttemptId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkerSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkerSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkerSummary(/** @type {Partial<WorkerSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BuyerAccountBadge.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = domain$0.TaskGroup.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = AccountSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = BuyerWithAccounts.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = WorkerSummary.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = MacroSummary.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = AttemptSummary.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = domain$0.PurchaseGroup.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = CatalogSKU.createFrom;
const $$createType17 = $Create.Array($$createType16);
