// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Generator defines the token generation strategy for Bilibili ticket ordering.
 * @typedef {$models.Generator} Generator
 */
