// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * VersionInfo holds the version information for any plugin.
 */
export class VersionInfo {
    /**
     * Creates a new VersionInfo instance.
     * @param {Partial<VersionInfo>} [$$source = {}] - The source object to create the VersionInfo.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * e.g. "captcha-plugin"
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("GitCommit" in $$source)) {
            /**
             * e.g. "a1b2c3d"
             * @member
             * @type {string}
             */
            this["GitCommit"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * e.g. "0.3.2"
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo(/** @type {Partial<VersionInfo>} */($$parsedSource));
    }
}
