// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogBroker manages per-task log rings and pushes real-time entries to the
 * frontend via Wails runtime events. It is exposed as a Wails binding so the
 * frontend can call GetHistory / ClearHistory directly.
 * Logs are persisted to disk via LogStorage so they survive application restarts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory clears both the in-memory ring buffer and the persisted logs
 * for a specific task.
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory(taskID) {
    return $Call.ByID(2778324631, taskID);
}

/**
 * CloseStream closes the forwarding channel for the given task and removes
 * the in-memory ring buffer. Persisted logs on disk are preserved. Safe to
 * call multiple times.
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function CloseStream(taskID) {
    return $Call.ByID(2534429724, taskID);
}

/**
 * CreateStream returns a send-only channel that the task uses to emit logs.
 * A background goroutine reads from this channel, stores entries in the ring
 * buffer, and fires frontend events. The caller may close the returned channel
 * to clean up the forwarding goroutine, or call CloseStream(taskID) to do so
 * from the outside.
 * @param {string} taskID
 * @returns {$CancellablePromise<any>}
 */
export function CreateStream(taskID) {
    return $Call.ByID(3210131132, taskID);
}

/**
 * FlushLogs immediately persists all pending log writes to disk.
 * Should be called on application shutdown.
 * @returns {$CancellablePromise<void>}
 */
export function FlushLogs() {
    return $Call.ByID(3486311213);
}

/**
 * GetHistory returns all log entries for a task from persistent storage,
 * falling back to the in-memory ring buffer if nothing has been persisted yet.
 * This is a Wails binding called by the frontend when entering a task view.
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.LogEntry[]>}
 */
export function GetHistory(taskID) {
    return $Call.ByID(101842892, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetPersistedTaskIDs returns the IDs of all tasks that have logs persisted on disk.
 * This is a Wails binding useful for showing historical task log availability.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPersistedTaskIDs() {
    return $Call.ByID(1620552214).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetRecentLogs returns the most recent log entry for every known task.
 * Useful for a dashboard overview.
 * @returns {$CancellablePromise<{ [_ in string]?: $models.LogEntry }>}
 */
export function GetRecentLogs() {
    return $Call.ByID(1331594092).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PutLog is exported as a Wails binding so the Go backend can also push logs
 * programmatically. Usually tasks will use the channel from CreateStream instead.
 * @param {string} taskID
 * @param {$models.LogLevel} level
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function PutLog(taskID, level, message) {
    return $Call.ByID(3278430029, taskID, level, message);
}

/**
 * SetApp stores the Wails v3 application reference for event emitting.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(374177819, app);
}

// Private type creation functions
const $$createType0 = $models.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $$createType0);
