// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * FrontendBWSEntry mirrors BWSEntry for Wails serialization.
 */
export class FrontendBWSEntry {
    /**
     * Creates a new FrontendBWSEntry instance.
     * @param {Partial<FrontendBWSEntry>} [$$source = {}] - The source object to create the FrontendBWSEntry.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("activityId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activityId"] = 0;
        }
        if (!("ticketNo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ticketNo"] = "";
        }
        if (!("activityTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activityTitle"] = "";
        }
        if (!("reserveTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reserveTime"] = 0;
        }
        if (!("reserveDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reserveDate"] = "";
        }
        if (!("expire" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expire"] = 0;
        }
        if (!("startDelayMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startDelayMs"] = 0;
        }
        if (!("loopDelayMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["loopDelayMs"] = 0;
        }
        if (!("stat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stat"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendBWSEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FrontendBWSEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FrontendBWSEntry(/** @type {Partial<FrontendBWSEntry>} */($$parsedSource));
    }
}

/**
 * FrontendBuyer is a simplified buyer struct for the frontend real-name picker.
 */
export class FrontendBuyer {
    /**
     * Creates a new FrontendBuyer instance.
     * @param {Partial<FrontendBuyer>} [$$source = {}] - The source object to create the FrontendBuyer.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("tel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tel"] = "";
        }
        if (!("personalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["personalId"] = "";
        }
        if (!("idType" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["idType"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendBuyer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FrontendBuyer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FrontendBuyer(/** @type {Partial<FrontendBuyer>} */($$parsedSource));
    }
}

/**
 * FrontendNotifyChannel mirrors NotifyChannel for Wails serialization.
 */
export class FrontendNotifyChannel {
    /**
     * Creates a new FrontendNotifyChannel instance.
     * @param {Partial<FrontendNotifyChannel>} [$$source = {}] - The source object to create the FrontendNotifyChannel.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("params" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["params"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendNotifyChannel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FrontendNotifyChannel}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField4_0($$parsedSource["params"]);
        }
        return new FrontendNotifyChannel(/** @type {Partial<FrontendNotifyChannel>} */($$parsedSource));
    }
}

/**
 * FrontendTaskStatus mirrors TaskStatus but serializes error to string.
 */
export class FrontendTaskStatus {
    /**
     * Creates a new FrontendTaskStatus instance.
     * @param {Partial<FrontendTaskStatus>} [$$source = {}] - The source object to create the FrontendTaskStatus.
     */
    constructor($$source = {}) {
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("targetTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetTime"] = "";
        }
        if (!("adjustedTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["adjustedTime"] = "";
        }
        if (!("remainingMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remainingMs"] = 0;
        }
        if (!("stat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stat"] = 0;
        }
        if (!("statName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("projectName" in $$source)) {
            /**
             * Ticket info for display
             * @member
             * @type {string}
             */
            this["projectName"] = "";
        }
        if (!("screenName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenName"] = "";
        }
        if (!("skuName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skuName"] = "";
        }
        if (!("buyerName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buyerName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendTaskStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FrontendTaskStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FrontendTaskStatus(/** @type {Partial<FrontendTaskStatus>} */($$parsedSource));
    }
}

/**
 * FrontendTicket mirrors TicketEntry for Wails serialization.
 */
export class FrontendTicket {
    /**
     * Creates a new FrontendTicket instance.
     * @param {Partial<FrontendTicket>} [$$source = {}] - The source object to create the FrontendTicket.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("expire" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expire"] = 0;
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectId"] = 0;
        }
        if (!("projectName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectName"] = "";
        }
        if (!("skuId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skuId"] = 0;
        }
        if (!("skuName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skuName"] = "";
        }
        if (!("screenId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["screenId"] = 0;
        }
        if (!("screenName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenName"] = "";
        }
        if (!("buyers" in $$source)) {
            /**
             * @member
             * @type {FrontendBuyer[]}
             */
            this["buyers"] = [];
        }
        if (!("stat" in $$source)) {
            /**
             * Stat persists the task execution result (RunningStat).
             * @member
             * @type {number}
             */
            this["stat"] = 0;
        }
        if (!("sortOrder" in $$source)) {
            /**
             * SortOrder is the chain order within the same buyer group.
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendTicket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FrontendTicket}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("buyers" in $$parsedSource) {
            $$parsedSource["buyers"] = $$createField9_0($$parsedSource["buyers"]);
        }
        return new FrontendTicket(/** @type {Partial<FrontendTicket>} */($$parsedSource));
    }
}

/**
 * LogEntry is a single structured log line emitted by a task.
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {LogLevel}
             */
            this["level"] = LogLevel.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * LogLevel represents the severity level of a log entry.
 * @readonly
 * @enum {string}
 */
export const LogLevel = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LogDebug: "debug",
    LogInfo: "info",
    LogWarn: "warn",
    LogError: "error",
    LogSuccess: "success",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = FrontendBuyer.createFrom;
const $$createType2 = $Create.Array($$createType1);
