// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchedulerService bridges the scheduler, BiliClient and LogBroker to the
 * Wails frontend. It is bound as a Wails service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notify$0 from "../notify/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddBWSEntry persists a BWS entry and returns its hash.
 * @param {$models.FrontendBWSEntry} entry
 * @returns {$CancellablePromise<string>}
 */
export function AddBWSEntry(entry) {
    return $Call.ByID(1713954802, entry);
}

/**
 * AddBWSTask creates a BWSTask from a persisted BWS entry hash and starts it.
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function AddBWSTask(hash) {
    return $Call.ByID(19107383, hash);
}

/**
 * AddNotifyChannel adds a new notification channel and rebuilds the MultiNotifier.
 * @param {$models.FrontendNotifyChannel} ch
 * @returns {$CancellablePromise<number>}
 */
export function AddNotifyChannel(ch) {
    return $Call.ByID(3777700982, ch);
}

/**
 * AddTicket adds a ticket to persistent storage and returns its hash.
 * @param {$models.FrontendTicket} ticket
 * @returns {$CancellablePromise<string>}
 */
export function AddTicket(ticket) {
    return $Call.ByID(3250411726, ticket);
}

/**
 * AddTicketTask is retained only for old generated frontend bindings.
 * Membership-ticket execution moved to the employer ClusterService.
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function AddTicketTask(hash) {
    return $Call.ByID(2533695187, hash);
}

/**
 * FetchRealNameBuyers obtains the real-name buyer list for a given project/sku/screen.
 * Returns a list of verified buyers the user can choose from.
 * Works for both hot and normal projects.
 * @returns {$CancellablePromise<$models.FrontendBuyer[]>}
 */
export function FetchRealNameBuyers() {
    return $Call.ByID(4063907562).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ForceStartTask instantly executes a task, bypassing its timer.
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function ForceStartTask(hash) {
    return $Call.ByID(2719759391, hash);
}

/**
 * GetAllTickets returns all saved ticket entries as FrontendTicket.
 * @returns {$CancellablePromise<$models.FrontendTicket[]>}
 */
export function GetAllTickets() {
    return $Call.ByID(2477004805).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetBWSEntries returns all saved BWS entries.
 * @returns {$CancellablePromise<$models.FrontendBWSEntry[]>}
 */
export function GetBWSEntries() {
    return $Call.ByID(4104341201).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetBilibiliOffset returns the last measured Bilibili API clock offset in milliseconds.
 * @returns {$CancellablePromise<number>}
 */
export function GetBilibiliOffset() {
    return $Call.ByID(4095138670);
}

/**
 * GetChainTrigger returns the current chain-switch trigger mode.
 * "success" = only switch to the next ticket on success;
 * "any" = switch on any terminal state.
 * @returns {$CancellablePromise<string>}
 */
export function GetChainTrigger() {
    return $Call.ByID(1390999018);
}

/**
 * GetGlobalOffset returns the current clock offset (server time − local time) in milliseconds.
 * Positive means local clock is behind the server.
 * @returns {$CancellablePromise<number>}
 */
export function GetGlobalOffset() {
    return $Call.ByID(1401201301);
}

/**
 * GetNTPOffset returns the last measured NTP clock offset in milliseconds.
 * @returns {$CancellablePromise<number>}
 */
export function GetNTPOffset() {
    return $Call.ByID(2223879078);
}

/**
 * GetNotifyChannelTypes returns metadata for all supported notification channel types.
 * The frontend uses this to dynamically render the channel configuration form.
 * @returns {$CancellablePromise<notify$0.NotifyChannelTypeMeta[]>}
 */
export function GetNotifyChannelTypes() {
    return $Call.ByID(1840631264).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetNotifyChannels returns all configured notification channels.
 * @returns {$CancellablePromise<$models.FrontendNotifyChannel[]>}
 */
export function GetNotifyChannels() {
    return $Call.ByID(3857480904).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetRetryInterval returns the global retry interval in milliseconds.
 * @returns {$CancellablePromise<number>}
 */
export function GetRetryInterval() {
    return $Call.ByID(1407050712);
}

/**
 * GetStartDelay returns the global start delay (one-time initial delay) in milliseconds.
 * @returns {$CancellablePromise<number>}
 */
export function GetStartDelay() {
    return $Call.ByID(2015538938);
}

/**
 * GetTaskStatuses returns the current status of all scheduled tasks,
 * enriched with ticket display names.
 * @returns {$CancellablePromise<$models.FrontendTaskStatus[]>}
 */
export function GetTaskStatuses() {
    return $Call.ByID(2984758458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ReloadBWSTasks starts tasks for all valid BWS entries that are not yet
 * scheduled. Call this on startup to recover persisted entries.
 * Completed tasks (StatSuccess/StatFailed/StatError) are not re-scheduled.
 * @returns {$CancellablePromise<void>}
 */
export function ReloadBWSTasks() {
    return $Call.ByID(3661163768);
}

/**
 * ReloadTickets starts tasks for all valid tickets that are not yet scheduled.
 * Call this on startup to recover persisted tickets.
 * Completed tasks (StatSuccess/StatFailed/StatError) are not re-scheduled.
 * 
 * For chainable tickets (real-name, same project), only the first waiting
 * ticket (smallest SortOrder) in each chain group is started. The rest are
 * triggered automatically by chain switching when the previous one terminates.
 * Non-chainable tickets (ordinary) are all started independently.
 * @returns {$CancellablePromise<void>}
 */
export function ReloadTickets() {
    return $Call.ByID(3812859571);
}

/**
 * RemoveBWSEntry removes a BWS entry from storage and its associated task.
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function RemoveBWSEntry(hash) {
    return $Call.ByID(3319499019, hash);
}

/**
 * RemoveNotifyChannel removes a notification channel at the given index.
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function RemoveNotifyChannel(index) {
    return $Call.ByID(1028124649, index);
}

/**
 * RemoveTask stops and removes a task by its ticket hash.
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTask(hash) {
    return $Call.ByID(3195765186, hash);
}

/**
 * RemoveTicket removes a ticket from storage and its associated task (if any).
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTicket(hash) {
    return $Call.ByID(1262190299, hash);
}

/**
 * ReorderTickets rewrites the chain order (SortOrder) of the tickets
 * identified by orderedHashes so they form an ascending chain within the
 * buyer group of the first hash. The change is persisted to disk.
 * Pass the full ordered list of hashes for the group (in the desired order).
 * 
 * If the reorder changes which task should be currently running (the first
 * waiting ticket in the new order differs from the currently running one),
 * the previously running task is stopped and the new first one is started.
 * @param {string[]} orderedHashes
 * @returns {$CancellablePromise<void>}
 */
export function ReorderTickets(orderedHashes) {
    return $Call.ByID(2277903643, orderedHashes);
}

/**
 * SetApp stores the Wails v3 application reference for window management.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1814299244, app);
}

/**
 * SetChainTrigger updates the chain-switch trigger mode and persists it.
 * Accepts "success" or "any"; any other value is normalized to "success".
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetChainTrigger(mode) {
    return $Call.ByID(1691260030, mode);
}

/**
 * SetRetryInterval updates the global retry interval (ms), persists it,
 * and broadcasts the change to all currently running tasks.
 * @param {number} ms
 * @returns {$CancellablePromise<void>}
 */
export function SetRetryInterval(ms) {
    return $Call.ByID(4051466356, ms);
}

/**
 * SetStartDelay updates the global start delay (ms, 0-500), persists it,
 * and broadcasts the change to all currently running tasks.
 * @param {number} ms
 * @returns {$CancellablePromise<void>}
 */
export function SetStartDelay(ms) {
    return $Call.ByID(2863269950, ms);
}

/**
 * StartClockCalibration begins a background goroutine that periodically
 * calibrates the scheduler's global time offset against Bilibili's server
 * clock (with NTP fallback). Calibration runs every clockCalibrationInterval
 * (default 120s).
 * @returns {$CancellablePromise<void>}
 */
export function StartClockCalibration() {
    return $Call.ByID(1113125071);
}

/**
 * StopClockCalibration stops the background clock calibration goroutine.
 * @returns {$CancellablePromise<void>}
 */
export function StopClockCalibration() {
    return $Call.ByID(3954332053);
}

/**
 * TestNotifyChannel sends a test message through the specified channel.
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function TestNotifyChannel(index) {
    return $Call.ByID(2931658913, index);
}

/**
 * UpdateNotifyChannel updates a notification channel at the given index.
 * @param {number} index
 * @param {$models.FrontendNotifyChannel} ch
 * @returns {$CancellablePromise<void>}
 */
export function UpdateNotifyChannel(index, ch) {
    return $Call.ByID(4289312818, index, ch);
}

// Private type creation functions
const $$createType0 = $models.FrontendBuyer.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FrontendTicket.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.FrontendBWSEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = notify$0.NotifyChannelTypeMeta.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.FrontendNotifyChannel.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.FrontendTaskStatus.createFrom;
const $$createType11 = $Create.Array($$createType10);
