// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BWSMyReservationItemStruct is a single item in the user's my-reservation list.
 */
export class BWSMyReservationItemStruct {
    /**
     * Creates a new BWSMyReservationItemStruct instance.
     * @param {Partial<BWSMyReservationItemStruct>} [$$source = {}] - The source object to create the BWSMyReservationItemStruct.
     */
    constructor($$source = {}) {
        if (!("act_title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["act_title"] = "";
        }
        if (!("reserve_no" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reserve_no"] = "";
        }
        if (!("act_begin_time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["act_begin_time"] = 0;
        }
        if (!("act_end_time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["act_end_time"] = 0;
        }
        if (!("reserve_location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reserve_location"] = "";
        }
        if (!("is_checked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["is_checked"] = 0;
        }
        if (!("online_state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["online_state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BWSMyReservationItemStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BWSMyReservationItemStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BWSMyReservationItemStruct(/** @type {Partial<BWSMyReservationItemStruct>} */($$parsedSource));
    }
}

/**
 * BWSMyReservationsStruct represents the response from
 * GET /x/activity/bws/online/park/myreserve
 */
export class BWSMyReservationsStruct {
    /**
     * Creates a new BWSMyReservationsStruct instance.
     * @param {Partial<BWSMyReservationsStruct>} [$$source = {}] - The source object to create the BWSMyReservationsStruct.
     */
    constructor($$source = {}) {
        if (!("reserve_list" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: BWSMyReservationItemStruct[] }}
             */
            this["reserve_list"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BWSMyReservationsStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BWSMyReservationsStruct}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reserve_list" in $$parsedSource) {
            $$parsedSource["reserve_list"] = $$createField0_0($$parsedSource["reserve_list"]);
        }
        return new BWSMyReservationsStruct(/** @type {Partial<BWSMyReservationsStruct>} */($$parsedSource));
    }
}

export class BiliAppVersionStruct {
    /**
     * Creates a new BiliAppVersionStruct instance.
     * @param {Partial<BiliAppVersionStruct>} [$$source = {}] - The source object to create the BiliAppVersionStruct.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("build" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["build"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BiliAppVersionStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BiliAppVersionStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BiliAppVersionStruct(/** @type {Partial<BiliAppVersionStruct>} */($$parsedSource));
    }
}

/**
 * BuyerListInfo contains the buyer list and max purchase limit for order confirmation.
 */
export class BuyerListInfo {
    /**
     * Creates a new BuyerListInfo instance.
     * @param {Partial<BuyerListInfo>} [$$source = {}] - The source object to create the BuyerListInfo.
     */
    constructor($$source = {}) {
        if (!("list" in $$source)) {
            /**
             * @member
             * @type {BuyerStruct[]}
             */
            this["list"] = [];
        }
        if (!("max_limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuyerListInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuyerListInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("list" in $$parsedSource) {
            $$parsedSource["list"] = $$createField0_0($$parsedSource["list"]);
        }
        return new BuyerListInfo(/** @type {Partial<BuyerListInfo>} */($$parsedSource));
    }
}

export class BuyerNoSensitiveStruct {
    /**
     * Creates a new BuyerNoSensitiveStruct instance.
     * @param {Partial<BuyerNoSensitiveStruct>} [$$source = {}] - The source object to create the BuyerNoSensitiveStruct.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uid"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("idType" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["idType"] = 0;
        }
        if (!("idName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["idName"] = "";
        }
        if (!("idCard" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["idCard"] = "";
        }
        if (!("tel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tel"] = "";
        }
        if (!("viewType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["viewType"] = "";
        }
        if (!("verifyStatus" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verifyStatus"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuyerNoSensitiveStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuyerNoSensitiveStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuyerNoSensitiveStruct(/** @type {Partial<BuyerNoSensitiveStruct>} */($$parsedSource));
    }
}

export class BuyerStruct {
    /**
     * Creates a new BuyerStruct instance.
     * @param {Partial<BuyerStruct>} [$$source = {}] - The source object to create the BuyerStruct.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uid"] = 0;
        }
        if (!("accountId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["accountId"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("buyer" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["buyer"] = null;
        }
        if (!("tel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tel"] = "";
        }
        if (!("disabledErr" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["disabledErr"] = null;
        }
        if (!("account_channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_channel"] = "";
        }
        if (!("personal_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["personal_id"] = "";
        }
        if (!("id_card_front" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id_card_front"] = "";
        }
        if (!("id_card_back" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id_card_back"] = "";
        }
        if (!("is_default" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["is_default"] = 0;
        }
        if (!("id_type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id_type"] = 0;
        }
        if (!("verify_status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verify_status"] = 0;
        }
        if (!("isBuyerInfoVerified" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isBuyerInfoVerified"] = false;
        }
        if (!("isBuyerValid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isBuyerValid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuyerStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuyerStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuyerStruct(/** @type {Partial<BuyerStruct>} */($$parsedSource));
    }
}

export class ConfirmStruct {
    /**
     * Creates a new ConfirmStruct instance.
     * @param {Partial<ConfirmStruct>} [$$source = {}] - The source object to create the ConfirmStruct.
     */
    constructor($$source = {}) {
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("buyerList" in $$source)) {
            /**
             * @member
             * @type {BuyerListInfo}
             */
            this["buyerList"] = (new BuyerListInfo());
        }
        if (!("hotProject" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hotProject"] = false;
        }
        if (!("orderCreateUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["orderCreateUrl"] = "";
        }
        if (!("project_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["project_id"] = 0;
        }
        if (!("project_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_name"] = "";
        }
        if (!("screen_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["screen_id"] = 0;
        }
        if (!("screen_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screen_name"] = "";
        }
        if (!("buyer_info" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buyer_info"] = "";
        }
        if (!("item_total_money" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["item_total_money"] = 0;
        }
        if (!("pay_money" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pay_money"] = 0;
        }
        if (!("ticket_info" in $$source)) {
            /**
             * @member
             * @type {TicketInfoDetail}
             */
            this["ticket_info"] = (new TicketInfoDetail());
        }
        if (!("id_bind" in $$source)) {
            /**
             * 0 = 无实名, 1 = 单人实名可买多张票, 2 = 一票一实名
             * @member
             * @type {number}
             */
            this["id_bind"] = 0;
        }
        if (!("is_package" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["is_package"] = 0;
        }
        if (!("need_contact" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["need_contact"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfirmStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfirmStruct}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        const $$createField11_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("buyerList" in $$parsedSource) {
            $$parsedSource["buyerList"] = $$createField1_0($$parsedSource["buyerList"]);
        }
        if ("ticket_info" in $$parsedSource) {
            $$parsedSource["ticket_info"] = $$createField11_0($$parsedSource["ticket_info"]);
        }
        return new ConfirmStruct(/** @type {Partial<ConfirmStruct>} */($$parsedSource));
    }
}

export class GetLoginInfoStruct {
    /**
     * Creates a new GetLoginInfoStruct instance.
     * @param {Partial<GetLoginInfoStruct>} [$$source = {}] - The source object to create the GetLoginInfoStruct.
     */
    constructor($$source = {}) {
        if (!("isLogin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLogin"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["uname"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["mid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["face"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetLoginInfoStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetLoginInfoStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetLoginInfoStruct(/** @type {Partial<GetLoginInfoStruct>} */($$parsedSource));
    }
}

export class OrderStatusStruct {
    /**
     * Creates a new OrderStatusStruct instance.
     * @param {Partial<OrderStatusStruct>} [$$source = {}] - The source object to create the OrderStatusStruct.
     */
    constructor($$source = {}) {
        if (!("order_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["order_id"] = "";
        }
        if (!("payParam" in $$source)) {
            /**
             * @member
             * @type {{"code_url": string, "orderCreateTime": string, "orderExpire": string}}
             */
            this["payParam"] = {"code_url": "", "orderCreateTime": "", "orderExpire": ""};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderStatusStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OrderStatusStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrderStatusStruct(/** @type {Partial<OrderStatusStruct>} */($$parsedSource));
    }
}

export class QRLoginKeyStruct {
    /**
     * Creates a new QRLoginKeyStruct instance.
     * @param {Partial<QRLoginKeyStruct>} [$$source = {}] - The source object to create the QRLoginKeyStruct.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("qrcode_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["qrcode_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QRLoginKeyStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QRLoginKeyStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QRLoginKeyStruct(/** @type {Partial<QRLoginKeyStruct>} */($$parsedSource));
    }
}

/**
 * TicketInfoDetail contains the ticket price, count, and SKU info for order confirmation.
 */
export class TicketInfoDetail {
    /**
     * Creates a new TicketInfoDetail instance.
     * @param {Partial<TicketInfoDetail>} [$$source = {}] - The source object to create the TicketInfoDetail.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("price" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["price"] = 0;
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("sku_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sku_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketInfoDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketInfoDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketInfoDetail(/** @type {Partial<TicketInfoDetail>} */($$parsedSource));
    }
}

export class TicketOrderStruct {
    /**
     * Creates a new TicketOrderStruct instance.
     * @param {Partial<TicketOrderStruct>} [$$source = {}] - The source object to create the TicketOrderStruct.
     */
    constructor($$source = {}) {
        if (!("orderId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["orderId"] = 0;
        }
        if (!("orderCreateTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["orderCreateTime"] = 0;
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("pay_money" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pay_money"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketOrderStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TicketOrderStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TicketOrderStruct(/** @type {Partial<TicketOrderStruct>} */($$parsedSource));
    }
}

export class VerifyQRLoginStateStruct {
    /**
     * Creates a new VerifyQRLoginStateStruct instance.
     * @param {Partial<VerifyQRLoginStateStruct>} [$$source = {}] - The source object to create the VerifyQRLoginStateStruct.
     */
    constructor($$source = {}) {
        if (!("refresh_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refresh_token"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["code"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerifyQRLoginStateStruct instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VerifyQRLoginStateStruct}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VerifyQRLoginStateStruct(/** @type {Partial<VerifyQRLoginStateStruct>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BWSMyReservationItemStruct.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = BuyerStruct.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = BuyerListInfo.createFrom;
const $$createType6 = TicketInfoDetail.createFrom;
