// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Client handles the lifecycle of a plugin application. It launches
 * plugins, connects to them, dispenses interface implementations, and handles
 * killing the process.
 * 
 * Plugin hosts should use one Client for each plugin executable. To
 * dispense a plugin type, use the `Client.Client` function, and then
 * call `Dispense`. This awkward API is mostly historical but is used to split
 * the client that deals with subprocess management and the client that
 * does RPC management.
 * 
 * See NewClient and ClientConfig for using a Client.
 */
export class Client {
    /**
     * Creates a new Client instance.
     * @param {Partial<Client>} [$$source = {}] - The source object to create the Client.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Client}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Client(/** @type {Partial<Client>} */($$parsedSource));
    }
}
