// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * @readonly
 * @enum {string}
 */
export const AttemptState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AttemptQueued: "queued",
    AttemptWaiting: "waiting",
    AttemptRunning: "running",
    AttemptStopping: "stopping",
    AttemptStopped: "stopped",
    AttemptSucceeded: "succeeded",
    AttemptFailed: "failed",
};

export class Buyer {
    /**
     * Creates a new Buyer instance.
     * @param {Partial<Buyer>} [$$source = {}] - The source object to create the Buyer.
     */
    constructor($$source = {}) {
        if (!("logicalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logicalId"] = "";
        }
        if (!("buyerId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["buyerId"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["idCard"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["type"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Buyer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Buyer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Buyer(/** @type {Partial<Buyer>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const CapacitySource = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CapacityAPI: "api",
    CapacityOverride: "override",
    CapacityDefault: "default",
};

/**
 * @readonly
 * @enum {string}
 */
export const FailureReason = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FailureNone: "",
    FailureDeadline: "deadline",
    FailureStopped: "stopped",
    FailureCookieInvalid: "cookie_invalid",
    FailureHTTP412: "http_412",
    FailureCaptcha: "captcha",
    FailureAccountRisk: "account_risk",
    FailureWorkerLost: "worker_lost",
    FailureUnrecoverable: "unrecoverable",
    FailureInternal: "internal",
};

/**
 * @readonly
 * @enum {string}
 */
export const Phase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PhasePunctual: "punctual",
    PhaseReflow: "reflow",
};

export class PurchaseGroup {
    /**
     * Creates a new PurchaseGroup instance.
     * @param {Partial<PurchaseGroup>} [$$source = {}] - The source object to create the PurchaseGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("macroTaskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["macroTaskId"] = "";
        }
        if (!("buyers" in $$source)) {
            /**
             * @member
             * @type {Buyer[]}
             */
            this["buyers"] = [];
        }
        if (!("allowSplit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allowSplit"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PurchaseGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PurchaseGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("buyers" in $$parsedSource) {
            $$parsedSource["buyers"] = $$createField2_0($$parsedSource["buyers"]);
        }
        return new PurchaseGroup(/** @type {Partial<PurchaseGroup>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ResourceRole = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RolePrimary: "primary",
    RoleStandby: "standby",
};

export class TaskGroup {
    /**
     * Creates a new TaskGroup instance.
     * @param {Partial<TaskGroup>} [$$source = {}] - The source object to create the TaskGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskGroup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskGroup(/** @type {Partial<TaskGroup>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Buyer.createFrom;
const $$createType1 = $Create.Array($$createType0);
