//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../../../../../bilibili-ticket-golang/lib/biliutils/scheduler/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "ticket:log": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = scheduler$0.LogEntry.createFrom;

configure();
