/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPicker: typeof import('./components/cluster/AccountPicker.vue')['default']
    AnnouncementFloatingCard: typeof import('./components/AnnouncementFloatingCard.vue')['default']
    GeetestCaptcha: typeof import('./components/GeetestCaptcha.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerifiedOverlay: typeof import('./components/VerifiedOverlay.vue')['default']
    WorkerPicker: typeof import('./components/cluster/WorkerPicker.vue')['default']
  }
}
