// Helper functions for scheduler types generated by Wails v3 bindings.

import type * as scheduler from '../../bindings/bilibili-ticket-golang/lib/biliutils/scheduler/models'
import type * as notify from '../../bindings/bilibili-ticket-golang/lib/biliutils/notify/models'

// Re-export for convenience
export type FrontendTaskStatus = scheduler.FrontendTaskStatus
export type FrontendTicket = scheduler.FrontendTicket
export type FrontendBWSEntry = scheduler.FrontendBWSEntry
export type LogEntry = scheduler.LogEntry
export type FrontendNotifyChannel = scheduler.FrontendNotifyChannel
export type NotifyChannelFieldMeta = notify.NotifyChannelFieldMeta
export type NotifyChannelTypeMeta = notify.NotifyChannelTypeMeta
// RunningStat enum values from Go
export const StatWaiting = 0
export const StatPending = 1
export const StatSuccess = 2
export const StatFailed = 3
export const StatError = 4

export function statLabel(s: number): string {
    switch (s) {
        case StatWaiting: return '等待中'
        case StatPending: return '执行中'
        case StatSuccess: return '已成功'
        case StatFailed: return '已失败'
        case StatError: return '错误'
        default: return '未知'
    }
}

export function statColor(s: number): string {
    switch (s) {
        case StatWaiting: return 'blue'
        case StatPending: return 'orange'
        case StatSuccess: return 'green'
        case StatFailed: return 'grey'
        case StatError: return 'red'
        default: return 'grey'
    }
}
