// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: cluster/worker/proto/worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Health_FullMethodName                = "/worker.WorkerService/Health"
	WorkerService_Submit_FullMethodName                = "/worker.WorkerService/Submit"
	WorkerService_Status_FullMethodName                = "/worker.WorkerService/Status"
	WorkerService_Logs_FullMethodName                  = "/worker.WorkerService/Logs"
	WorkerService_Stop_FullMethodName                  = "/worker.WorkerService/Stop"
	WorkerService_Ack_FullMethodName                   = "/worker.WorkerService/Ack"
	WorkerService_Heartbeat_FullMethodName             = "/worker.WorkerService/Heartbeat"
	WorkerService_Configure_FullMethodName             = "/worker.WorkerService/Configure"
	WorkerService_ListBuyers_FullMethodName            = "/worker.WorkerService/ListBuyers"
	WorkerService_CreateBuyer_FullMethodName           = "/worker.WorkerService/CreateBuyer"
	WorkerService_GetBuyerSensitiveData_FullMethodName = "/worker.WorkerService/GetBuyerSensitiveData"
	WorkerService_ListBuyersMasked_FullMethodName      = "/worker.WorkerService/ListBuyersMasked"
	WorkerService_DeleteBuyer_FullMethodName           = "/worker.WorkerService/DeleteBuyer"
	WorkerService_CheckBWSBind_FullMethodName          = "/worker.WorkerService/CheckBWSBind"
	WorkerService_GetBWSReservationInfo_FullMethodName = "/worker.WorkerService/GetBWSReservationInfo"
	WorkerService_BindBWSTicket_FullMethodName         = "/worker.WorkerService/BindBWSTicket"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerServiceClient interface {
	// Health returns the worker's health and metadata.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Submit creates a new task or returns an existing one idempotently.
	// Returns ALREADY_EXISTS if attemptId exists with a different spec.
	// Returns RESOURCE_EXHAUSTED if the worker is already busy.
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	// Status returns the current status of a task, renewing its lease.
	// Returns NOT_FOUND if the attempt is unknown.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Logs returns all log entries for a task.
	// Returns NOT_FOUND if the attempt is unknown.
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error)
	// Stop requests cancellation of a running task.
	// Returns NOT_FOUND if the attempt is unknown.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Ack acknowledges a terminal task, allowing the worker to clean up.
	// Returns NOT_FOUND if the attempt is unknown.
	// Returns FAILED_PRECONDITION if the attempt is not terminal.
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
	// Heartbeat is a bidirectional stream for liveness detection.
	// The worker periodically sends HeartbeatMsg; the master echoes them
	// back. Either side treats silence longer than the heartbeat interval
	// as a dead connection, triggering a reconnect.
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatMsg, HeartbeatMsg], error)
	// Configure pushes global settings (retry interval, start delay) from
	// the employer to the worker. The worker applies these immediately to
	// all future tasks. The employer calls this after a successful Health
	// handshake and whenever the user changes settings.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// ListBuyers fetches the full (unmasked) real‑name buyer list from a
	// Bilibili account.  The worker uses the supplied credentials to log
	// into the Bilibili API and returns the refreshed credentials so the
	// employer can persist the updated cookie/version state.
	ListBuyers(ctx context.Context, in *ListBuyersRequest, opts ...grpc.CallOption) (*ListBuyersResponse, error)
	// CreateBuyer provisions a new real‑name buyer on a Bilibili account
	// and returns the created buyer (with its assigned Bilibili buyer_id)
	// together with refreshed credentials.
	CreateBuyer(ctx context.Context, in *CreateBuyerRequest, opts ...grpc.CallOption) (*CreateBuyerResponse, error)
	// GetBuyerSensitiveData fetches the full unmasked real‑name
	// information (ID card number, phone, etc.) for a specific buyer
	// already on a Bilibili account's real‑name list.
	GetBuyerSensitiveData(ctx context.Context, in *GetBuyerSensitiveDataRequest, opts ...grpc.CallOption) (*GetBuyerSensitiveDataResponse, error)
	// ListBuyersMasked fetches the buyer list without unmasking sensitive
	// data.  ID cards and phone numbers may be returned with asterisks
	// (masked).  Use this to quickly enumerate buyers from many accounts
	// without rate-limiting, then call GetBuyerSensitiveData only for
	// unique logical buyers that need full real‑name information.
	ListBuyersMasked(ctx context.Context, in *ListBuyersRequest, opts ...grpc.CallOption) (*ListBuyersResponse, error)
	// DeleteBuyer removes a real‑name buyer from a Bilibili account.
	DeleteBuyer(ctx context.Context, in *DeleteBuyerRequest, opts ...grpc.CallOption) (*DeleteBuyerResponse, error)
	// CheckBWSBind checks whether the account has a BWS electronic ticket
	// bound to a real‑name identity.
	CheckBWSBind(ctx context.Context, in *CheckBWSBindRequest, opts ...grpc.CallOption) (*CheckBWSBindResponse, error)
	// GetBWSReservationInfo fetches all BWS activity information for the
	// given dates.
	GetBWSReservationInfo(ctx context.Context, in *BWSReservationInfoRequest, opts ...grpc.CallOption) (*BWSReservationInfoResponse, error)
	// BindBWSTicket binds a real‑name identity to an electronic ticket.
	BindBWSTicket(ctx context.Context, in *BindBWSTicketRequest, opts ...grpc.CallOption) (*BindBWSTicketResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, WorkerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, WorkerService_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, WorkerService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsResponse)
	err := c.cc.Invoke(ctx, WorkerService_Logs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, WorkerService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, WorkerService_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatMsg, HeartbeatMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatMsg, HeartbeatMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatMsg, HeartbeatMsg]

func (c *workerServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, WorkerService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListBuyers(ctx context.Context, in *ListBuyersRequest, opts ...grpc.CallOption) (*ListBuyersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuyersResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListBuyers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CreateBuyer(ctx context.Context, in *CreateBuyerRequest, opts ...grpc.CallOption) (*CreateBuyerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBuyerResponse)
	err := c.cc.Invoke(ctx, WorkerService_CreateBuyer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetBuyerSensitiveData(ctx context.Context, in *GetBuyerSensitiveDataRequest, opts ...grpc.CallOption) (*GetBuyerSensitiveDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuyerSensitiveDataResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetBuyerSensitiveData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListBuyersMasked(ctx context.Context, in *ListBuyersRequest, opts ...grpc.CallOption) (*ListBuyersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuyersResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListBuyersMasked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DeleteBuyer(ctx context.Context, in *DeleteBuyerRequest, opts ...grpc.CallOption) (*DeleteBuyerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBuyerResponse)
	err := c.cc.Invoke(ctx, WorkerService_DeleteBuyer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CheckBWSBind(ctx context.Context, in *CheckBWSBindRequest, opts ...grpc.CallOption) (*CheckBWSBindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBWSBindResponse)
	err := c.cc.Invoke(ctx, WorkerService_CheckBWSBind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetBWSReservationInfo(ctx context.Context, in *BWSReservationInfoRequest, opts ...grpc.CallOption) (*BWSReservationInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BWSReservationInfoResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetBWSReservationInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) BindBWSTicket(ctx context.Context, in *BindBWSTicketRequest, opts ...grpc.CallOption) (*BindBWSTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindBWSTicketResponse)
	err := c.cc.Invoke(ctx, WorkerService_BindBWSTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
type WorkerServiceServer interface {
	// Health returns the worker's health and metadata.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Submit creates a new task or returns an existing one idempotently.
	// Returns ALREADY_EXISTS if attemptId exists with a different spec.
	// Returns RESOURCE_EXHAUSTED if the worker is already busy.
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	// Status returns the current status of a task, renewing its lease.
	// Returns NOT_FOUND if the attempt is unknown.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Logs returns all log entries for a task.
	// Returns NOT_FOUND if the attempt is unknown.
	Logs(context.Context, *LogsRequest) (*LogsResponse, error)
	// Stop requests cancellation of a running task.
	// Returns NOT_FOUND if the attempt is unknown.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Ack acknowledges a terminal task, allowing the worker to clean up.
	// Returns NOT_FOUND if the attempt is unknown.
	// Returns FAILED_PRECONDITION if the attempt is not terminal.
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	// Heartbeat is a bidirectional stream for liveness detection.
	// The worker periodically sends HeartbeatMsg; the master echoes them
	// back. Either side treats silence longer than the heartbeat interval
	// as a dead connection, triggering a reconnect.
	Heartbeat(grpc.BidiStreamingServer[HeartbeatMsg, HeartbeatMsg]) error
	// Configure pushes global settings (retry interval, start delay) from
	// the employer to the worker. The worker applies these immediately to
	// all future tasks. The employer calls this after a successful Health
	// handshake and whenever the user changes settings.
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// ListBuyers fetches the full (unmasked) real‑name buyer list from a
	// Bilibili account.  The worker uses the supplied credentials to log
	// into the Bilibili API and returns the refreshed credentials so the
	// employer can persist the updated cookie/version state.
	ListBuyers(context.Context, *ListBuyersRequest) (*ListBuyersResponse, error)
	// CreateBuyer provisions a new real‑name buyer on a Bilibili account
	// and returns the created buyer (with its assigned Bilibili buyer_id)
	// together with refreshed credentials.
	CreateBuyer(context.Context, *CreateBuyerRequest) (*CreateBuyerResponse, error)
	// GetBuyerSensitiveData fetches the full unmasked real‑name
	// information (ID card number, phone, etc.) for a specific buyer
	// already on a Bilibili account's real‑name list.
	GetBuyerSensitiveData(context.Context, *GetBuyerSensitiveDataRequest) (*GetBuyerSensitiveDataResponse, error)
	// ListBuyersMasked fetches the buyer list without unmasking sensitive
	// data.  ID cards and phone numbers may be returned with asterisks
	// (masked).  Use this to quickly enumerate buyers from many accounts
	// without rate-limiting, then call GetBuyerSensitiveData only for
	// unique logical buyers that need full real‑name information.
	ListBuyersMasked(context.Context, *ListBuyersRequest) (*ListBuyersResponse, error)
	// DeleteBuyer removes a real‑name buyer from a Bilibili account.
	DeleteBuyer(context.Context, *DeleteBuyerRequest) (*DeleteBuyerResponse, error)
	// CheckBWSBind checks whether the account has a BWS electronic ticket
	// bound to a real‑name identity.
	CheckBWSBind(context.Context, *CheckBWSBindRequest) (*CheckBWSBindResponse, error)
	// GetBWSReservationInfo fetches all BWS activity information for the
	// given dates.
	GetBWSReservationInfo(context.Context, *BWSReservationInfoRequest) (*BWSReservationInfoResponse, error)
	// BindBWSTicket binds a real‑name identity to an electronic ticket.
	BindBWSTicket(context.Context, *BindBWSTicketRequest) (*BindBWSTicketResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedWorkerServiceServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedWorkerServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedWorkerServiceServer) Logs(context.Context, *LogsRequest) (*LogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedWorkerServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedWorkerServiceServer) Ack(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedWorkerServiceServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatMsg, HeartbeatMsg]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedWorkerServiceServer) ListBuyers(context.Context, *ListBuyersRequest) (*ListBuyersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuyers not implemented")
}
func (UnimplementedWorkerServiceServer) CreateBuyer(context.Context, *CreateBuyerRequest) (*CreateBuyerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBuyer not implemented")
}
func (UnimplementedWorkerServiceServer) GetBuyerSensitiveData(context.Context, *GetBuyerSensitiveDataRequest) (*GetBuyerSensitiveDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBuyerSensitiveData not implemented")
}
func (UnimplementedWorkerServiceServer) ListBuyersMasked(context.Context, *ListBuyersRequest) (*ListBuyersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuyersMasked not implemented")
}
func (UnimplementedWorkerServiceServer) DeleteBuyer(context.Context, *DeleteBuyerRequest) (*DeleteBuyerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBuyer not implemented")
}
func (UnimplementedWorkerServiceServer) CheckBWSBind(context.Context, *CheckBWSBindRequest) (*CheckBWSBindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBWSBind not implemented")
}
func (UnimplementedWorkerServiceServer) GetBWSReservationInfo(context.Context, *BWSReservationInfoRequest) (*BWSReservationInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBWSReservationInfo not implemented")
}
func (UnimplementedWorkerServiceServer) BindBWSTicket(context.Context, *BindBWSTicketRequest) (*BindBWSTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindBWSTicket not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Logs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Logs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Logs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Logs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).Heartbeat(&grpc.GenericServerStream[HeartbeatMsg, HeartbeatMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatMsg, HeartbeatMsg]

func _WorkerService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListBuyers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuyersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListBuyers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListBuyers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListBuyers(ctx, req.(*ListBuyersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CreateBuyer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuyerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CreateBuyer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CreateBuyer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CreateBuyer(ctx, req.(*CreateBuyerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetBuyerSensitiveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuyerSensitiveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetBuyerSensitiveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetBuyerSensitiveData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetBuyerSensitiveData(ctx, req.(*GetBuyerSensitiveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListBuyersMasked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuyersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListBuyersMasked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListBuyersMasked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListBuyersMasked(ctx, req.(*ListBuyersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DeleteBuyer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBuyerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DeleteBuyer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DeleteBuyer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DeleteBuyer(ctx, req.(*DeleteBuyerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CheckBWSBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBWSBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CheckBWSBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CheckBWSBind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CheckBWSBind(ctx, req.(*CheckBWSBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetBWSReservationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BWSReservationInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetBWSReservationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetBWSReservationInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetBWSReservationInfo(ctx, req.(*BWSReservationInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_BindBWSTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindBWSTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).BindBWSTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_BindBWSTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).BindBWSTicket(ctx, req.(*BindBWSTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _WorkerService_Health_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _WorkerService_Submit_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _WorkerService_Status_Handler,
		},
		{
			MethodName: "Logs",
			Handler:    _WorkerService_Logs_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _WorkerService_Stop_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _WorkerService_Ack_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _WorkerService_Configure_Handler,
		},
		{
			MethodName: "ListBuyers",
			Handler:    _WorkerService_ListBuyers_Handler,
		},
		{
			MethodName: "CreateBuyer",
			Handler:    _WorkerService_CreateBuyer_Handler,
		},
		{
			MethodName: "GetBuyerSensitiveData",
			Handler:    _WorkerService_GetBuyerSensitiveData_Handler,
		},
		{
			MethodName: "ListBuyersMasked",
			Handler:    _WorkerService_ListBuyersMasked_Handler,
		},
		{
			MethodName: "DeleteBuyer",
			Handler:    _WorkerService_DeleteBuyer_Handler,
		},
		{
			MethodName: "CheckBWSBind",
			Handler:    _WorkerService_CheckBWSBind_Handler,
		},
		{
			MethodName: "GetBWSReservationInfo",
			Handler:    _WorkerService_GetBWSReservationInfo_Handler,
		},
		{
			MethodName: "BindBWSTicket",
			Handler:    _WorkerService_BindBWSTicket_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _WorkerService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cluster/worker/proto/worker.proto",
}
