// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: worker.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttemptState int32

const (
	AttemptState_ATTEMPT_QUEUED    AttemptState = 0
	AttemptState_ATTEMPT_WAITING   AttemptState = 1
	AttemptState_ATTEMPT_RUNNING   AttemptState = 2
	AttemptState_ATTEMPT_STOPPING  AttemptState = 3
	AttemptState_ATTEMPT_STOPPED   AttemptState = 4
	AttemptState_ATTEMPT_SUCCEEDED AttemptState = 5
	AttemptState_ATTEMPT_FAILED    AttemptState = 6
)

// Enum value maps for AttemptState.
var (
	AttemptState_name = map[int32]string{
		0: "ATTEMPT_QUEUED",
		1: "ATTEMPT_WAITING",
		2: "ATTEMPT_RUNNING",
		3: "ATTEMPT_STOPPING",
		4: "ATTEMPT_STOPPED",
		5: "ATTEMPT_SUCCEEDED",
		6: "ATTEMPT_FAILED",
	}
	AttemptState_value = map[string]int32{
		"ATTEMPT_QUEUED":    0,
		"ATTEMPT_WAITING":   1,
		"ATTEMPT_RUNNING":   2,
		"ATTEMPT_STOPPING":  3,
		"ATTEMPT_STOPPED":   4,
		"ATTEMPT_SUCCEEDED": 5,
		"ATTEMPT_FAILED":    6,
	}
)

func (x AttemptState) Enum() *AttemptState {
	p := new(AttemptState)
	*p = x
	return p
}

func (x AttemptState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttemptState) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (AttemptState) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x AttemptState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttemptState.Descriptor instead.
func (AttemptState) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

type StartMode int32

const (
	StartMode_START_IMMEDIATE StartMode = 0
	StartMode_START_SCHEDULED StartMode = 1
)

// Enum value maps for StartMode.
var (
	StartMode_name = map[int32]string{
		0: "START_IMMEDIATE",
		1: "START_SCHEDULED",
	}
	StartMode_value = map[string]int32{
		"START_IMMEDIATE": 0,
		"START_SCHEDULED": 1,
	}
)

func (x StartMode) Enum() *StartMode {
	p := new(StartMode)
	*p = x
	return p
}

func (x StartMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartMode) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[1].Descriptor()
}

func (StartMode) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[1]
}

func (x StartMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartMode.Descriptor instead.
func (StartMode) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

type FailureReason int32

const (
	FailureReason_FAILURE_NONE           FailureReason = 0
	FailureReason_FAILURE_DEADLINE       FailureReason = 1
	FailureReason_FAILURE_STOPPED        FailureReason = 2
	FailureReason_FAILURE_COOKIE_INVALID FailureReason = 3
	FailureReason_FAILURE_HTTP_412       FailureReason = 4
	FailureReason_FAILURE_CAPTCHA        FailureReason = 5
	FailureReason_FAILURE_ACCOUNT_RISK   FailureReason = 6
	FailureReason_FAILURE_WORKER_LOST    FailureReason = 7
	FailureReason_FAILURE_UNRECOVERABLE  FailureReason = 8
	FailureReason_FAILURE_INTERNAL       FailureReason = 9
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "FAILURE_NONE",
		1: "FAILURE_DEADLINE",
		2: "FAILURE_STOPPED",
		3: "FAILURE_COOKIE_INVALID",
		4: "FAILURE_HTTP_412",
		5: "FAILURE_CAPTCHA",
		6: "FAILURE_ACCOUNT_RISK",
		7: "FAILURE_WORKER_LOST",
		8: "FAILURE_UNRECOVERABLE",
		9: "FAILURE_INTERNAL",
	}
	FailureReason_value = map[string]int32{
		"FAILURE_NONE":           0,
		"FAILURE_DEADLINE":       1,
		"FAILURE_STOPPED":        2,
		"FAILURE_COOKIE_INVALID": 3,
		"FAILURE_HTTP_412":       4,
		"FAILURE_CAPTCHA":        5,
		"FAILURE_ACCOUNT_RISK":   6,
		"FAILURE_WORKER_LOST":    7,
		"FAILURE_UNRECOVERABLE":  8,
		"FAILURE_INTERNAL":       9,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[2].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[2]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

type Buyer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalId     string                 `protobuf:"bytes,1,opt,name=logical_id,json=logicalId,proto3" json:"logical_id,omitempty"`
	BuyerId       int64                  `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tel           string                 `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel,omitempty"`
	IdCard        string                 `protobuf:"bytes,5,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Type          int32                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buyer) Reset() {
	*x = Buyer{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buyer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buyer) ProtoMessage() {}

func (x *Buyer) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buyer.ProtoReflect.Descriptor instead.
func (*Buyer) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *Buyer) GetLogicalId() string {
	if x != nil {
		return x.LogicalId
	}
	return ""
}

func (x *Buyer) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *Buyer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Buyer) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *Buyer) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *Buyer) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookies       map[string]string      `protobuf:"bytes,1,rep,name=cookies,proto3" json:"cookies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CookieJar     []*HTTPCookie          `protobuf:"bytes,2,rep,name=cookie_jar,json=cookieJar,proto3" json:"cookie_jar,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	DeviceProfile []byte                 `protobuf:"bytes,5,opt,name=device_profile,json=deviceProfile,proto3" json:"device_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetCookies() map[string]string {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *Credentials) GetCookieJar() []*HTTPCookie {
	if x != nil {
		return x.CookieJar
	}
	return nil
}

func (x *Credentials) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Credentials) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Credentials) GetDeviceProfile() []byte {
	if x != nil {
		return x.DeviceProfile
	}
	return nil
}

type HTTPCookie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Secure        bool                   `protobuf:"varint,5,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool                   `protobuf:"varint,6,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	Expires       int64                  `protobuf:"varint,7,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPCookie) Reset() {
	*x = HTTPCookie{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPCookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPCookie) ProtoMessage() {}

func (x *HTTPCookie) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPCookie.ProtoReflect.Descriptor instead.
func (*HTTPCookie) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPCookie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HTTPCookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *HTTPCookie) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *HTTPCookie) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPCookie) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *HTTPCookie) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

func (x *HTTPCookie) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type ExecutionSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	IntentId      string                 `protobuf:"bytes,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ScreenId      int64                  `protobuf:"varint,4,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,5,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Buyers        []*Buyer               `protobuf:"bytes,6,rep,name=buyers,proto3" json:"buyers,omitempty"`
	StartMode     StartMode              `protobuf:"varint,7,opt,name=start_mode,json=startMode,proto3,enum=worker.StartMode" json:"start_mode,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	IntervalMs    int64                  `protobuf:"varint,10,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	Credentials   *Credentials           `protobuf:"bytes,11,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionSpec) Reset() {
	*x = ExecutionSpec{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSpec) ProtoMessage() {}

func (x *ExecutionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSpec.ProtoReflect.Descriptor instead.
func (*ExecutionSpec) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionSpec) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ExecutionSpec) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *ExecutionSpec) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ExecutionSpec) GetScreenId() int64 {
	if x != nil {
		return x.ScreenId
	}
	return 0
}

func (x *ExecutionSpec) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *ExecutionSpec) GetBuyers() []*Buyer {
	if x != nil {
		return x.Buyers
	}
	return nil
}

func (x *ExecutionSpec) GetStartMode() StartMode {
	if x != nil {
		return x.StartMode
	}
	return StartMode_START_IMMEDIATE
}

func (x *ExecutionSpec) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *ExecutionSpec) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *ExecutionSpec) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *ExecutionSpec) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type ExecutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	IntentId      string                 `protobuf:"bytes,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	SpecHash      string                 `protobuf:"bytes,3,opt,name=spec_hash,json=specHash,proto3" json:"spec_hash,omitempty"`
	State         AttemptState           `protobuf:"varint,4,opt,name=state,proto3,enum=worker.AttemptState" json:"state,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	OrderId       string                 `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        FailureReason          `protobuf:"varint,7,opt,name=reason,proto3,enum=worker.FailureReason" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,9,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Credentials   *Credentials           `protobuf:"bytes,10,opt,name=credentials,proto3" json:"credentials,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,13,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	PaymentExpire int64                  `protobuf:"varint,14,opt,name=payment_expire,json=paymentExpire,proto3" json:"payment_expire,omitempty"`
	OrderTime     int64                  `protobuf:"varint,15,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionResult) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ExecutionResult) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *ExecutionResult) GetSpecHash() string {
	if x != nil {
		return x.SpecHash
	}
	return ""
}

func (x *ExecutionResult) GetState() AttemptState {
	if x != nil {
		return x.State
	}
	return AttemptState_ATTEMPT_QUEUED
}

func (x *ExecutionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecutionResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ExecutionResult) GetReason() FailureReason {
	if x != nil {
		return x.Reason
	}
	return FailureReason_FAILURE_NONE
}

func (x *ExecutionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionResult) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ExecutionResult) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ExecutionResult) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecutionResult) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ExecutionResult) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *ExecutionResult) GetPaymentExpire() int64 {
	if x != nil {
		return x.PaymentExpire
	}
	return 0
}

func (x *ExecutionResult) GetOrderTime() int64 {
	if x != nil {
		return x.OrderTime
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Retryable     bool                   `protobuf:"varint,6,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *LogEntry) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LogEntry) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogEntry) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LogEntry) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	SpecHash      string                 `protobuf:"bytes,2,opt,name=spec_hash,json=specHash,proto3" json:"spec_hash,omitempty"`
	State         AttemptState           `protobuf:"varint,3,opt,name=state,proto3,enum=worker.AttemptState" json:"state,omitempty"`
	LeaseUntil    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`
	Result        *ExecutionResult       `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *TaskStatus) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskStatus) GetSpecHash() string {
	if x != nil {
		return x.SpecHash
	}
	return ""
}

func (x *TaskStatus) GetState() AttemptState {
	if x != nil {
		return x.State
	}
	return AttemptState_ATTEMPT_QUEUED
}

func (x *TaskStatus) GetLeaseUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseUntil
	}
	return nil
}

func (x *TaskStatus) GetResult() *ExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PluginVersion    string                 `protobuf:"bytes,3,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	AlgorithmVersion string                 `protobuf:"bytes,4,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	CaptchaPlugin    string                 `protobuf:"bytes,5,opt,name=captcha_plugin,json=captchaPlugin,proto3" json:"captcha_plugin,omitempty"`
	ClockCalibration bool                   `protobuf:"varint,6,opt,name=clock_calibration,json=clockCalibration,proto3" json:"clock_calibration,omitempty"`
	ActiveAttemptId  string                 `protobuf:"bytes,7,opt,name=active_attempt_id,json=activeAttemptId,proto3" json:"active_attempt_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *HealthResponse) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *HealthResponse) GetCaptchaPlugin() string {
	if x != nil {
		return x.CaptchaPlugin
	}
	return ""
}

func (x *HealthResponse) GetClockCalibration() bool {
	if x != nil {
		return x.ClockCalibration
	}
	return false
}

func (x *HealthResponse) GetActiveAttemptId() string {
	if x != nil {
		return x.ActiveAttemptId
	}
	return ""
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ExecutionSpec         `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitRequest) GetSpec() *ExecutionSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *TaskStatus            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitResponse) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

func (x *StatusRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *TaskStatus            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{13}
}

func (x *LogsRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{14}
}

func (x *LogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{15}
}

func (x *StopRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *TaskStatus            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{16}
}

func (x *StopResponse) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{17}
}

func (x *AckRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{18}
}

type HeartbeatMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ActiveAttemptId string                 `protobuf:"bytes,2,opt,name=active_attempt_id,json=activeAttemptId,proto3" json:"active_attempt_id,omitempty"`
	Sequence        int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	CompletedTask   *ExecutionResult       `protobuf:"bytes,5,opt,name=completed_task,json=completedTask,proto3" json:"completed_task,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	mi := &file_worker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{19}
}

func (x *HeartbeatMsg) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatMsg) GetActiveAttemptId() string {
	if x != nil {
		return x.ActiveAttemptId
	}
	return ""
}

func (x *HeartbeatMsg) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HeartbeatMsg) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *HeartbeatMsg) GetCompletedTask() *ExecutionResult {
	if x != nil {
		return x.CompletedTask
	}
	return nil
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x06worker\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x01\n" +
	"\x05Buyer\x12\x1d\n" +
	"\n" +
	"logical_id\x18\x01 \x01(\tR\tlogicalId\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x03R\abuyerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03tel\x18\x04 \x01(\tR\x03tel\x12\x17\n" +
	"\aid_card\x18\x05 \x01(\tR\x06idCard\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x05R\x04type\"\x9e\x02\n" +
	"\vCredentials\x12:\n" +
	"\acookies\x18\x01 \x03(\v2 .worker.Credentials.CookiesEntryR\acookies\x121\n" +
	"\n" +
	"cookie_jar\x18\x02 \x03(\v2\x12.worker.HTTPCookieR\tcookieJar\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12%\n" +
	"\x0edevice_profile\x18\x05 \x01(\fR\rdeviceProfile\x1a:\n" +
	"\fCookiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\n" +
	"HTTPCookie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06secure\x18\x05 \x01(\bR\x06secure\x12\x1b\n" +
	"\thttp_only\x18\x06 \x01(\bR\bhttpOnly\x12\x18\n" +
	"\aexpires\x18\a \x01(\x03R\aexpires\"\xbe\x03\n" +
	"\rExecutionSpec\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\tR\bintentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x03R\tprojectId\x12\x1b\n" +
	"\tscreen_id\x18\x04 \x01(\x03R\bscreenId\x12\x15\n" +
	"\x06sku_id\x18\x05 \x01(\x03R\x05skuId\x12%\n" +
	"\x06buyers\x18\x06 \x03(\v2\r.worker.BuyerR\x06buyers\x120\n" +
	"\n" +
	"start_mode\x18\a \x01(\x0e2\x11.worker.StartModeR\tstartMode\x125\n" +
	"\bstart_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x126\n" +
	"\bdeadline\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1f\n" +
	"\vinterval_ms\x18\n" +
	" \x01(\x03R\n" +
	"intervalMs\x125\n" +
	"\vcredentials\x18\v \x01(\v2\x13.worker.CredentialsR\vcredentials\"\xc8\x04\n" +
	"\x0fExecutionResult\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\tR\bintentId\x12\x1b\n" +
	"\tspec_hash\x18\x03 \x01(\tR\bspecHash\x12*\n" +
	"\x05state\x18\x04 \x01(\x0e2\x14.worker.AttemptStateR\x05state\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId\x12-\n" +
	"\x06reason\x18\a \x01(\x0e2\x15.worker.FailureReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\t \x01(\bR\tretryable\x125\n" +
	"\vcredentials\x18\n" +
	" \x01(\v2\x13.worker.CredentialsR\vcredentials\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x1f\n" +
	"\vpayment_url\x18\r \x01(\tR\n" +
	"paymentUrl\x12%\n" +
	"\x0epayment_expire\x18\x0e \x01(\x03R\rpaymentExpire\x12\x1d\n" +
	"\n" +
	"order_time\x18\x0f \x01(\x03R\torderTime\"\xb8\x01\n" +
	"\bLogEntry\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12\x1c\n" +
	"\tretryable\x18\x06 \x01(\bR\tretryable\"\xe2\x01\n" +
	"\n" +
	"TaskStatus\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1b\n" +
	"\tspec_hash\x18\x02 \x01(\tR\bspecHash\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.worker.AttemptStateR\x05state\x12;\n" +
	"\vlease_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"leaseUntil\x12/\n" +
	"\x06result\x18\x05 \x01(\v2\x17.worker.ExecutionResultR\x06result\"\x0f\n" +
	"\rHealthRequest\"\x9b\x02\n" +
	"\x0eHealthResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0eplugin_version\x18\x03 \x01(\tR\rpluginVersion\x12+\n" +
	"\x11algorithm_version\x18\x04 \x01(\tR\x10algorithmVersion\x12%\n" +
	"\x0ecaptcha_plugin\x18\x05 \x01(\tR\rcaptchaPlugin\x12+\n" +
	"\x11clock_calibration\x18\x06 \x01(\bR\x10clockCalibration\x12*\n" +
	"\x11active_attempt_id\x18\a \x01(\tR\x0factiveAttemptId\":\n" +
	"\rSubmitRequest\x12)\n" +
	"\x04spec\x18\x01 \x01(\v2\x15.worker.ExecutionSpecR\x04spec\"<\n" +
	"\x0eSubmitResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.worker.TaskStatusR\x06status\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\"<\n" +
	"\x0eStatusResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.worker.TaskStatusR\x06status\",\n" +
	"\vLogsRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\":\n" +
	"\fLogsResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.worker.LogEntryR\aentries\",\n" +
	"\vStopRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\":\n" +
	"\fStopResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.worker.TaskStatusR\x06status\"+\n" +
	"\n" +
	"AckRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\"\r\n" +
	"\vAckResponse\"\xa3\x01\n" +
	"\fHeartbeatMsg\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12*\n" +
	"\x11active_attempt_id\x18\x02 \x01(\tR\x0factiveAttemptId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time*\xa2\x01\n" +
	"\fAttemptState\x12\x12\n" +
	"\x0eATTEMPT_QUEUED\x10\x00\x12\x13\n" +
	"\x0fATTEMPT_WAITING\x10\x01\x12\x13\n" +
	"\x0fATTEMPT_RUNNING\x10\x02\x12\x14\n" +
	"\x10ATTEMPT_STOPPING\x10\x03\x12\x13\n" +
	"\x0fATTEMPT_STOPPED\x10\x04\x12\x15\n" +
	"\x11ATTEMPT_SUCCEEDED\x10\x05\x12\x12\n" +
	"\x0eATTEMPT_FAILED\x10\x06*5\n" +
	"\tStartMode\x12\x13\n" +
	"\x0fSTART_IMMEDIATE\x10\x00\x12\x13\n" +
	"\x0fSTART_SCHEDULED\x10\x01*\xf7\x01\n" +
	"\rFailureReason\x12\x10\n" +
	"\fFAILURE_NONE\x10\x00\x12\x14\n" +
	"\x10FAILURE_DEADLINE\x10\x01\x12\x13\n" +
	"\x0fFAILURE_STOPPED\x10\x02\x12\x1a\n" +
	"\x16FAILURE_COOKIE_INVALID\x10\x03\x12\x14\n" +
	"\x10FAILURE_HTTP_412\x10\x04\x12\x13\n" +
	"\x0fFAILURE_CAPTCHA\x10\x05\x12\x18\n" +
	"\x14FAILURE_ACCOUNT_RISK\x10\x06\x12\x17\n" +
	"\x13FAILURE_WORKER_LOST\x10\a\x12\x19\n" +
	"\x15FAILURE_UNRECOVERABLE\x10\b\x12\x14\n" +
	"\x10FAILURE_INTERNAL\x10\t2\x8d\x03\n" +
	"\rWorkerService\x127\n" +
	"\x06Health\x12\x15.worker.HealthRequest\x1a\x16.worker.HealthResponse\x127\n" +
	"\x06Submit\x12\x15.worker.SubmitRequest\x1a\x16.worker.SubmitResponse\x127\n" +
	"\x06Status\x12\x15.worker.StatusRequest\x1a\x16.worker.StatusResponse\x121\n" +
	"\x04Logs\x12\x13.worker.LogsRequest\x1a\x14.worker.LogsResponse\x121\n" +
	"\x04Stop\x12\x13.worker.StopRequest\x1a\x14.worker.StopResponse\x12.\n" +
	"\x03Ack\x12\x12.worker.AckRequest\x1a\x13.worker.AckResponse\x12;\n" +
	"\tHeartbeat\x12\x14.worker.HeartbeatMsg\x1a\x14.worker.HeartbeatMsg(\x010\x01B-Z+bilibili-ticket-golang/cluster/worker/protob\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_worker_proto_goTypes = []any{
	(AttemptState)(0),             // 0: worker.AttemptState
	(StartMode)(0),                // 1: worker.StartMode
	(FailureReason)(0),            // 2: worker.FailureReason
	(*Buyer)(nil),                 // 3: worker.Buyer
	(*Credentials)(nil),           // 4: worker.Credentials
	(*HTTPCookie)(nil),            // 5: worker.HTTPCookie
	(*ExecutionSpec)(nil),         // 6: worker.ExecutionSpec
	(*ExecutionResult)(nil),       // 7: worker.ExecutionResult
	(*LogEntry)(nil),              // 8: worker.LogEntry
	(*TaskStatus)(nil),            // 9: worker.TaskStatus
	(*HealthRequest)(nil),         // 10: worker.HealthRequest
	(*HealthResponse)(nil),        // 11: worker.HealthResponse
	(*SubmitRequest)(nil),         // 12: worker.SubmitRequest
	(*SubmitResponse)(nil),        // 13: worker.SubmitResponse
	(*StatusRequest)(nil),         // 14: worker.StatusRequest
	(*StatusResponse)(nil),        // 15: worker.StatusResponse
	(*LogsRequest)(nil),           // 16: worker.LogsRequest
	(*LogsResponse)(nil),          // 17: worker.LogsResponse
	(*StopRequest)(nil),           // 18: worker.StopRequest
	(*StopResponse)(nil),          // 19: worker.StopResponse
	(*AckRequest)(nil),            // 20: worker.AckRequest
	(*AckResponse)(nil),           // 21: worker.AckResponse
	(*HeartbeatMsg)(nil),          // 22: worker.HeartbeatMsg
	nil,                           // 23: worker.Credentials.CookiesEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_worker_proto_depIdxs = []int32{
	23, // 0: worker.Credentials.cookies:type_name -> worker.Credentials.CookiesEntry
	5,  // 1: worker.Credentials.cookie_jar:type_name -> worker.HTTPCookie
	3,  // 2: worker.ExecutionSpec.buyers:type_name -> worker.Buyer
	1,  // 3: worker.ExecutionSpec.start_mode:type_name -> worker.StartMode
	24, // 4: worker.ExecutionSpec.start_at:type_name -> google.protobuf.Timestamp
	24, // 5: worker.ExecutionSpec.deadline:type_name -> google.protobuf.Timestamp
	4,  // 6: worker.ExecutionSpec.credentials:type_name -> worker.Credentials
	0,  // 7: worker.ExecutionResult.state:type_name -> worker.AttemptState
	2,  // 8: worker.ExecutionResult.reason:type_name -> worker.FailureReason
	4,  // 9: worker.ExecutionResult.credentials:type_name -> worker.Credentials
	24, // 10: worker.ExecutionResult.started_at:type_name -> google.protobuf.Timestamp
	24, // 11: worker.ExecutionResult.finished_at:type_name -> google.protobuf.Timestamp
	24, // 12: worker.LogEntry.time:type_name -> google.protobuf.Timestamp
	0,  // 13: worker.TaskStatus.state:type_name -> worker.AttemptState
	24, // 14: worker.TaskStatus.lease_until:type_name -> google.protobuf.Timestamp
	7,  // 15: worker.TaskStatus.result:type_name -> worker.ExecutionResult
	6,  // 16: worker.SubmitRequest.spec:type_name -> worker.ExecutionSpec
	9,  // 17: worker.SubmitResponse.status:type_name -> worker.TaskStatus
	9,  // 18: worker.StatusResponse.status:type_name -> worker.TaskStatus
	8,  // 19: worker.LogsResponse.entries:type_name -> worker.LogEntry
	9,  // 20: worker.StopResponse.status:type_name -> worker.TaskStatus
	24, // 21: worker.HeartbeatMsg.time:type_name -> google.protobuf.Timestamp
	10, // 22: worker.WorkerService.Health:input_type -> worker.HealthRequest
	12, // 23: worker.WorkerService.Submit:input_type -> worker.SubmitRequest
	14, // 24: worker.WorkerService.Status:input_type -> worker.StatusRequest
	16, // 25: worker.WorkerService.Logs:input_type -> worker.LogsRequest
	18, // 26: worker.WorkerService.Stop:input_type -> worker.StopRequest
	20, // 27: worker.WorkerService.Ack:input_type -> worker.AckRequest
	22, // 28: worker.WorkerService.Heartbeat:input_type -> worker.HeartbeatMsg
	11, // 29: worker.WorkerService.Health:output_type -> worker.HealthResponse
	13, // 30: worker.WorkerService.Submit:output_type -> worker.SubmitResponse
	15, // 31: worker.WorkerService.Status:output_type -> worker.StatusResponse
	17, // 32: worker.WorkerService.Logs:output_type -> worker.LogsResponse
	19, // 33: worker.WorkerService.Stop:output_type -> worker.StopResponse
	21, // 34: worker.WorkerService.Ack:output_type -> worker.AckResponse
	22, // 35: worker.WorkerService.Heartbeat:output_type -> worker.HeartbeatMsg
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
