/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account': RouteRecordInfo<
      '/account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bws-reservation': RouteRecordInfo<
      '/bws-reservation',
      '/bws-reservation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notify': RouteRecordInfo<
      '/notify',
      '/notify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin-management': RouteRecordInfo<
      '/plugin-management',
      '/plugin-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugins-download': RouteRecordInfo<
      '/plugins-download',
      '/plugins-download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scheduler': RouteRecordInfo<
      '/scheduler',
      '/scheduler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ticket-overview': RouteRecordInfo<
      '/ticket-overview',
      '/ticket-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ticket-project': RouteRecordInfo<
      '/ticket-project',
      '/ticket-project',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/update': RouteRecordInfo<
      '/update',
      '/update',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/account.vue': {
      routes:
        | '/account'
      views:
        | never
    }
    'src/pages/bws-reservation.vue': {
      routes:
        | '/bws-reservation'
      views:
        | never
    }
    'src/pages/notify.vue': {
      routes:
        | '/notify'
      views:
        | never
    }
    'src/pages/plugin-management.vue': {
      routes:
        | '/plugin-management'
      views:
        | never
    }
    'src/pages/plugins-download.vue': {
      routes:
        | '/plugins-download'
      views:
        | never
    }
    'src/pages/scheduler.vue': {
      routes:
        | '/scheduler'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/ticket-overview.vue': {
      routes:
        | '/ticket-overview'
      views:
        | never
    }
    'src/pages/ticket-project.vue': {
      routes:
        | '/ticket-project'
      views:
        | never
    }
    'src/pages/update.vue': {
      routes:
        | '/update'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
