// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: plugins/proto/captcha.proto

package captcha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaptchaService_Solve_FullMethodName        = "/captcha.CaptchaService/Solve"
	CaptchaService_GetCS_FullMethodName        = "/captcha.CaptchaService/GetCS"
	CaptchaService_GetType_FullMethodName      = "/captcha.CaptchaService/GetType"
	CaptchaService_GetNewCSArgs_FullMethodName = "/captcha.CaptchaService/GetNewCSArgs"
	CaptchaService_CalculateKey_FullMethodName = "/captcha.CaptchaService/CalculateKey"
	CaptchaService_GenerateW_FullMethodName    = "/captcha.CaptchaService/GenerateW"
	CaptchaService_Verify_FullMethodName       = "/captcha.CaptchaService/Verify"
)

// CaptchaServiceClient is the client API for CaptchaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CaptchaService exposes both the high-level Solve pipeline and each
// fine-grained step, matching the Click / Slide API from old/captcha/geetest.go.
type CaptchaServiceClient interface {
	// Solve runs the full pipeline: GetCS → GetType → GetNewCSArgs → CalculateKey → GenerateW → Verify.
	Solve(ctx context.Context, in *SolveGeetestCaptchaRequest, opts ...grpc.CallOption) (*SolveGeetestCaptchaResponse, error)
	// Individual steps for callers that need fine-grained control.
	GetCS(ctx context.Context, in *GetCSRequest, opts ...grpc.CallOption) (*GetCSResponse, error)
	GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error)
	GetNewCSArgs(ctx context.Context, in *GetNewCSArgsRequest, opts ...grpc.CallOption) (*GetNewCSArgsResponse, error)
	CalculateKey(ctx context.Context, in *CalculateKeyRequest, opts ...grpc.CallOption) (*CalculateKeyResponse, error)
	GenerateW(ctx context.Context, in *GenerateWRequest, opts ...grpc.CallOption) (*GenerateWResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type captchaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptchaServiceClient(cc grpc.ClientConnInterface) CaptchaServiceClient {
	return &captchaServiceClient{cc}
}

func (c *captchaServiceClient) Solve(ctx context.Context, in *SolveGeetestCaptchaRequest, opts ...grpc.CallOption) (*SolveGeetestCaptchaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveGeetestCaptchaResponse)
	err := c.cc.Invoke(ctx, CaptchaService_Solve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaServiceClient) GetCS(ctx context.Context, in *GetCSRequest, opts ...grpc.CallOption) (*GetCSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCSResponse)
	err := c.cc.Invoke(ctx, CaptchaService_GetCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaServiceClient) GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*GetTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTypeResponse)
	err := c.cc.Invoke(ctx, CaptchaService_GetType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaServiceClient) GetNewCSArgs(ctx context.Context, in *GetNewCSArgsRequest, opts ...grpc.CallOption) (*GetNewCSArgsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewCSArgsResponse)
	err := c.cc.Invoke(ctx, CaptchaService_GetNewCSArgs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaServiceClient) CalculateKey(ctx context.Context, in *CalculateKeyRequest, opts ...grpc.CallOption) (*CalculateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateKeyResponse)
	err := c.cc.Invoke(ctx, CaptchaService_CalculateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaServiceClient) GenerateW(ctx context.Context, in *GenerateWRequest, opts ...grpc.CallOption) (*GenerateWResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateWResponse)
	err := c.cc.Invoke(ctx, CaptchaService_GenerateW_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, CaptchaService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptchaServiceServer is the server API for CaptchaService service.
// All implementations must embed UnimplementedCaptchaServiceServer
// for forward compatibility.
//
// CaptchaService exposes both the high-level Solve pipeline and each
// fine-grained step, matching the Click / Slide API from old/captcha/geetest.go.
type CaptchaServiceServer interface {
	// Solve runs the full pipeline: GetCS → GetType → GetNewCSArgs → CalculateKey → GenerateW → Verify.
	Solve(context.Context, *SolveGeetestCaptchaRequest) (*SolveGeetestCaptchaResponse, error)
	// Individual steps for callers that need fine-grained control.
	GetCS(context.Context, *GetCSRequest) (*GetCSResponse, error)
	GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error)
	GetNewCSArgs(context.Context, *GetNewCSArgsRequest) (*GetNewCSArgsResponse, error)
	CalculateKey(context.Context, *CalculateKeyRequest) (*CalculateKeyResponse, error)
	GenerateW(context.Context, *GenerateWRequest) (*GenerateWResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedCaptchaServiceServer()
}

// UnimplementedCaptchaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptchaServiceServer struct{}

func (UnimplementedCaptchaServiceServer) Solve(context.Context, *SolveGeetestCaptchaRequest) (*SolveGeetestCaptchaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedCaptchaServiceServer) GetCS(context.Context, *GetCSRequest) (*GetCSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCS not implemented")
}
func (UnimplementedCaptchaServiceServer) GetType(context.Context, *GetTypeRequest) (*GetTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetType not implemented")
}
func (UnimplementedCaptchaServiceServer) GetNewCSArgs(context.Context, *GetNewCSArgsRequest) (*GetNewCSArgsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewCSArgs not implemented")
}
func (UnimplementedCaptchaServiceServer) CalculateKey(context.Context, *CalculateKeyRequest) (*CalculateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateKey not implemented")
}
func (UnimplementedCaptchaServiceServer) GenerateW(context.Context, *GenerateWRequest) (*GenerateWResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateW not implemented")
}
func (UnimplementedCaptchaServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedCaptchaServiceServer) mustEmbedUnimplementedCaptchaServiceServer() {}
func (UnimplementedCaptchaServiceServer) testEmbeddedByValue()                        {}

// UnsafeCaptchaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptchaServiceServer will
// result in compilation errors.
type UnsafeCaptchaServiceServer interface {
	mustEmbedUnimplementedCaptchaServiceServer()
}

func RegisterCaptchaServiceServer(s grpc.ServiceRegistrar, srv CaptchaServiceServer) {
	// If the following call panics, it indicates UnimplementedCaptchaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptchaService_ServiceDesc, srv)
}

func _CaptchaService_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveGeetestCaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptchaService_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).Solve(ctx, req.(*SolveGeetestCaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaService_GetCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).GetCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptchaService_GetCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).GetCS(ctx, req.(*GetCSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaService_GetType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).GetType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptchaService_GetType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).GetType(ctx, req.(*GetTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaService_GetNewCSArgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewCSArgsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).GetNewCSArgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptchaService_GetNewCSArgs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).GetNewCSArgs(ctx, req.(*GetNewCSArgsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaService_CalculateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).CalculateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptchaService_CalculateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).CalculateKey(ctx, req.(*CalculateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaService_GenerateW_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).GenerateW(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptchaService_GenerateW_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).GenerateW(ctx, req.(*GenerateWRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptchaService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaptchaService_ServiceDesc is the grpc.ServiceDesc for CaptchaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptchaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "captcha.CaptchaService",
	HandlerType: (*CaptchaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _CaptchaService_Solve_Handler,
		},
		{
			MethodName: "GetCS",
			Handler:    _CaptchaService_GetCS_Handler,
		},
		{
			MethodName: "GetType",
			Handler:    _CaptchaService_GetType_Handler,
		},
		{
			MethodName: "GetNewCSArgs",
			Handler:    _CaptchaService_GetNewCSArgs_Handler,
		},
		{
			MethodName: "CalculateKey",
			Handler:    _CaptchaService_CalculateKey_Handler,
		},
		{
			MethodName: "GenerateW",
			Handler:    _CaptchaService_GenerateW_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _CaptchaService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins/proto/captcha.proto",
}
