// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: captcha.proto

package captcha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CaptchaType mirrors captcha.CaptchaType (SlideType / ClickType / UnknownType).
type CaptchaType int32

const (
	CaptchaType_UNKNOWN CaptchaType = 0
	CaptchaType_SLIDE   CaptchaType = 1
	CaptchaType_CLICK   CaptchaType = 2
)

// Enum value maps for CaptchaType.
var (
	CaptchaType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SLIDE",
		2: "CLICK",
	}
	CaptchaType_value = map[string]int32{
		"UNKNOWN": 0,
		"SLIDE":   1,
		"CLICK":   2,
	}
)

func (x CaptchaType) Enum() *CaptchaType {
	p := new(CaptchaType)
	*p = x
	return p
}

func (x CaptchaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaptchaType) Descriptor() protoreflect.EnumDescriptor {
	return file_captcha_proto_enumTypes[0].Descriptor()
}

func (CaptchaType) Type() protoreflect.EnumType {
	return &file_captcha_proto_enumTypes[0]
}

func (x CaptchaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaptchaType.Descriptor instead.
func (CaptchaType) EnumDescriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{0}
}

// GeetestCS holds the C/S data returned by GetCS.
// Corresponds to: type GeetestCS struct { s string; c []byte }
type GeetestCS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             string                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	C             []byte                 `protobuf:"bytes,2,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeetestCS) Reset() {
	*x = GeetestCS{}
	mi := &file_captcha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeetestCS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeetestCS) ProtoMessage() {}

func (x *GeetestCS) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeetestCS.ProtoReflect.Descriptor instead.
func (*GeetestCS) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{0}
}

func (x *GeetestCS) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *GeetestCS) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

// NewCSArgs bundles the arguments needed for CalculateKey / GenerateW.
// Corresponds to: type NewCSArgs struct { c, s, s1, s2, s3, s4 }
type NewCSArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             []byte                 `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	NewChallenge  string                 `protobuf:"bytes,3,opt,name=new_challenge,json=newChallenge,proto3" json:"new_challenge,omitempty"` // s1 – the new challenge string
	FullBgUrl     string                 `protobuf:"bytes,4,opt,name=full_bg_url,json=fullBgUrl,proto3" json:"full_bg_url,omitempty"`        // s2 – full background image URL
	MissBgUrl     string                 `protobuf:"bytes,5,opt,name=miss_bg_url,json=missBgUrl,proto3" json:"miss_bg_url,omitempty"`        // s3 – missing background image URL
	SliderUrl     string                 `protobuf:"bytes,6,opt,name=slider_url,json=sliderUrl,proto3" json:"slider_url,omitempty"`          // s4 – slider image URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewCSArgs) Reset() {
	*x = NewCSArgs{}
	mi := &file_captcha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewCSArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCSArgs) ProtoMessage() {}

func (x *NewCSArgs) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCSArgs.ProtoReflect.Descriptor instead.
func (*NewCSArgs) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{1}
}

func (x *NewCSArgs) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *NewCSArgs) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *NewCSArgs) GetNewChallenge() string {
	if x != nil {
		return x.NewChallenge
	}
	return ""
}

func (x *NewCSArgs) GetFullBgUrl() string {
	if x != nil {
		return x.FullBgUrl
	}
	return ""
}

func (x *NewCSArgs) GetMissBgUrl() string {
	if x != nil {
		return x.MissBgUrl
	}
	return ""
}

func (x *NewCSArgs) GetSliderUrl() string {
	if x != nil {
		return x.SliderUrl
	}
	return ""
}

type SolveGeetestCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gt            string                 `protobuf:"bytes,1,opt,name=gt,proto3" json:"gt,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveGeetestCaptchaRequest) Reset() {
	*x = SolveGeetestCaptchaRequest{}
	mi := &file_captcha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveGeetestCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveGeetestCaptchaRequest) ProtoMessage() {}

func (x *SolveGeetestCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveGeetestCaptchaRequest.ProtoReflect.Descriptor instead.
func (*SolveGeetestCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{2}
}

func (x *SolveGeetestCaptchaRequest) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *SolveGeetestCaptchaRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type SolveGeetestCaptchaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Validate      string                 `protobuf:"bytes,2,opt,name=validate,proto3" json:"validate,omitempty"` // the final validate string on success
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`       // error message on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveGeetestCaptchaResponse) Reset() {
	*x = SolveGeetestCaptchaResponse{}
	mi := &file_captcha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveGeetestCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveGeetestCaptchaResponse) ProtoMessage() {}

func (x *SolveGeetestCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveGeetestCaptchaResponse.ProtoReflect.Descriptor instead.
func (*SolveGeetestCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{3}
}

func (x *SolveGeetestCaptchaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SolveGeetestCaptchaResponse) GetValidate() string {
	if x != nil {
		return x.Validate
	}
	return ""
}

func (x *SolveGeetestCaptchaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gt            string                 `protobuf:"bytes,1,opt,name=gt,proto3" json:"gt,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	W             string                 `protobuf:"bytes,3,opt,name=w,proto3" json:"w,omitempty"` // optional; empty string means nil
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCSRequest) Reset() {
	*x = GetCSRequest{}
	mi := &file_captcha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCSRequest) ProtoMessage() {}

func (x *GetCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCSRequest.ProtoReflect.Descriptor instead.
func (*GetCSRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{4}
}

func (x *GetCSRequest) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *GetCSRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *GetCSRequest) GetW() string {
	if x != nil {
		return x.W
	}
	return ""
}

type GetCSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Cs            *GeetestCS             `protobuf:"bytes,2,opt,name=cs,proto3" json:"cs,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCSResponse) Reset() {
	*x = GetCSResponse{}
	mi := &file_captcha_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCSResponse) ProtoMessage() {}

func (x *GetCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCSResponse.ProtoReflect.Descriptor instead.
func (*GetCSResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{5}
}

func (x *GetCSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCSResponse) GetCs() *GeetestCS {
	if x != nil {
		return x.Cs
	}
	return nil
}

func (x *GetCSResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gt            string                 `protobuf:"bytes,1,opt,name=gt,proto3" json:"gt,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	W             string                 `protobuf:"bytes,3,opt,name=w,proto3" json:"w,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeRequest) Reset() {
	*x = GetTypeRequest{}
	mi := &file_captcha_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeRequest) ProtoMessage() {}

func (x *GetTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTypeRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{6}
}

func (x *GetTypeRequest) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *GetTypeRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *GetTypeRequest) GetW() string {
	if x != nil {
		return x.W
	}
	return ""
}

type GetTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Type          CaptchaType            `protobuf:"varint,2,opt,name=type,proto3,enum=captcha.CaptchaType" json:"type,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeResponse) Reset() {
	*x = GetTypeResponse{}
	mi := &file_captcha_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeResponse) ProtoMessage() {}

func (x *GetTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeResponse.ProtoReflect.Descriptor instead.
func (*GetTypeResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{7}
}

func (x *GetTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTypeResponse) GetType() CaptchaType {
	if x != nil {
		return x.Type
	}
	return CaptchaType_UNKNOWN
}

func (x *GetTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetNewCSArgsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gt            string                 `protobuf:"bytes,1,opt,name=gt,proto3" json:"gt,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewCSArgsRequest) Reset() {
	*x = GetNewCSArgsRequest{}
	mi := &file_captcha_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewCSArgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewCSArgsRequest) ProtoMessage() {}

func (x *GetNewCSArgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewCSArgsRequest.ProtoReflect.Descriptor instead.
func (*GetNewCSArgsRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{8}
}

func (x *GetNewCSArgsRequest) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *GetNewCSArgsRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type GetNewCSArgsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Args          *NewCSArgs             `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewCSArgsResponse) Reset() {
	*x = GetNewCSArgsResponse{}
	mi := &file_captcha_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewCSArgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewCSArgsResponse) ProtoMessage() {}

func (x *GetNewCSArgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewCSArgsResponse.ProtoReflect.Descriptor instead.
func (*GetNewCSArgsResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{9}
}

func (x *GetNewCSArgsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetNewCSArgsResponse) GetArgs() *NewCSArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *GetNewCSArgsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CalculateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gt            string                 `protobuf:"bytes,1,opt,name=gt,proto3" json:"gt,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Args          *NewCSArgs             `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateKeyRequest) Reset() {
	*x = CalculateKeyRequest{}
	mi := &file_captcha_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateKeyRequest) ProtoMessage() {}

func (x *CalculateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateKeyRequest.ProtoReflect.Descriptor instead.
func (*CalculateKeyRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{10}
}

func (x *CalculateKeyRequest) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *CalculateKeyRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *CalculateKeyRequest) GetArgs() *NewCSArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

type CalculateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateKeyResponse) Reset() {
	*x = CalculateKeyResponse{}
	mi := &file_captcha_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateKeyResponse) ProtoMessage() {}

func (x *CalculateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateKeyResponse.ProtoReflect.Descriptor instead.
func (*CalculateKeyResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{11}
}

func (x *CalculateKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CalculateKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CalculateKeyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GenerateWRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gt            string                 `protobuf:"bytes,1,opt,name=gt,proto3" json:"gt,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Args          *NewCSArgs             `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWRequest) Reset() {
	*x = GenerateWRequest{}
	mi := &file_captcha_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWRequest) ProtoMessage() {}

func (x *GenerateWRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWRequest.ProtoReflect.Descriptor instead.
func (*GenerateWRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateWRequest) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *GenerateWRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *GenerateWRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenerateWRequest) GetArgs() *NewCSArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

type GenerateWResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	W             string                 `protobuf:"bytes,2,opt,name=w,proto3" json:"w,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWResponse) Reset() {
	*x = GenerateWResponse{}
	mi := &file_captcha_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWResponse) ProtoMessage() {}

func (x *GenerateWResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWResponse.ProtoReflect.Descriptor instead.
func (*GenerateWResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateWResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateWResponse) GetW() string {
	if x != nil {
		return x.W
	}
	return ""
}

func (x *GenerateWResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gt            string                 `protobuf:"bytes,1,opt,name=gt,proto3" json:"gt,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	W             string                 `protobuf:"bytes,3,opt,name=w,proto3" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_captcha_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyRequest) GetGt() string {
	if x != nil {
		return x.Gt
	}
	return ""
}

func (x *VerifyRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *VerifyRequest) GetW() string {
	if x != nil {
		return x.W
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Validate      string                 `protobuf:"bytes,2,opt,name=validate,proto3" json:"validate,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_captcha_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyResponse) GetValidate() string {
	if x != nil {
		return x.Validate
	}
	return ""
}

func (x *VerifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_captcha_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{16}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitCommit     string                 `protobuf:"bytes,1,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_captcha_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{17}
}

func (x *VersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_captcha_proto protoreflect.FileDescriptor

const file_captcha_proto_rawDesc = "" +
	"\n" +
	"\rcaptcha.proto\x12\acaptcha\"'\n" +
	"\tGeetestCS\x12\f\n" +
	"\x01s\x18\x01 \x01(\tR\x01s\x12\f\n" +
	"\x01c\x18\x02 \x01(\fR\x01c\"\xab\x01\n" +
	"\tNewCSArgs\x12\f\n" +
	"\x01c\x18\x01 \x01(\fR\x01c\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12#\n" +
	"\rnew_challenge\x18\x03 \x01(\tR\fnewChallenge\x12\x1e\n" +
	"\vfull_bg_url\x18\x04 \x01(\tR\tfullBgUrl\x12\x1e\n" +
	"\vmiss_bg_url\x18\x05 \x01(\tR\tmissBgUrl\x12\x1d\n" +
	"\n" +
	"slider_url\x18\x06 \x01(\tR\tsliderUrl\"J\n" +
	"\x1aSolveGeetestCaptchaRequest\x12\x0e\n" +
	"\x02gt\x18\x01 \x01(\tR\x02gt\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\"i\n" +
	"\x1bSolveGeetestCaptchaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bvalidate\x18\x02 \x01(\tR\bvalidate\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"J\n" +
	"\fGetCSRequest\x12\x0e\n" +
	"\x02gt\x18\x01 \x01(\tR\x02gt\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12\f\n" +
	"\x01w\x18\x03 \x01(\tR\x01w\"c\n" +
	"\rGetCSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\x02cs\x18\x02 \x01(\v2\x12.captcha.GeetestCSR\x02cs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"L\n" +
	"\x0eGetTypeRequest\x12\x0e\n" +
	"\x02gt\x18\x01 \x01(\tR\x02gt\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12\f\n" +
	"\x01w\x18\x03 \x01(\tR\x01w\"k\n" +
	"\x0fGetTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.captcha.CaptchaTypeR\x04type\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"C\n" +
	"\x13GetNewCSArgsRequest\x12\x0e\n" +
	"\x02gt\x18\x01 \x01(\tR\x02gt\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\"n\n" +
	"\x14GetNewCSArgsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x04args\x18\x02 \x01(\v2\x12.captcha.NewCSArgsR\x04args\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"k\n" +
	"\x13CalculateKeyRequest\x12\x0e\n" +
	"\x02gt\x18\x01 \x01(\tR\x02gt\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12&\n" +
	"\x04args\x18\x03 \x01(\v2\x12.captcha.NewCSArgsR\x04args\"X\n" +
	"\x14CalculateKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"z\n" +
	"\x10GenerateWRequest\x12\x0e\n" +
	"\x02gt\x18\x01 \x01(\tR\x02gt\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12&\n" +
	"\x04args\x18\x04 \x01(\v2\x12.captcha.NewCSArgsR\x04args\"Q\n" +
	"\x11GenerateWResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\f\n" +
	"\x01w\x18\x02 \x01(\tR\x01w\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"K\n" +
	"\rVerifyRequest\x12\x0e\n" +
	"\x02gt\x18\x01 \x01(\tR\x02gt\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12\f\n" +
	"\x01w\x18\x03 \x01(\tR\x01w\"\\\n" +
	"\x0eVerifyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bvalidate\x18\x02 \x01(\tR\bvalidate\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x10\n" +
	"\x0eVersionRequest\"J\n" +
	"\x0fVersionResponse\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x01 \x01(\tR\tgitCommit\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion*0\n" +
	"\vCaptchaType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05SLIDE\x10\x01\x12\t\n" +
	"\x05CLICK\x10\x022\xaf\x04\n" +
	"\fClickService\x12R\n" +
	"\x05Solve\x12#.captcha.SolveGeetestCaptchaRequest\x1a$.captcha.SolveGeetestCaptchaResponse\x126\n" +
	"\x05GetCS\x12\x15.captcha.GetCSRequest\x1a\x16.captcha.GetCSResponse\x12<\n" +
	"\aGetType\x12\x17.captcha.GetTypeRequest\x1a\x18.captcha.GetTypeResponse\x12K\n" +
	"\fGetNewCSArgs\x12\x1c.captcha.GetNewCSArgsRequest\x1a\x1d.captcha.GetNewCSArgsResponse\x12K\n" +
	"\fCalculateKey\x12\x1c.captcha.CalculateKeyRequest\x1a\x1d.captcha.CalculateKeyResponse\x12B\n" +
	"\tGenerateW\x12\x19.captcha.GenerateWRequest\x1a\x1a.captcha.GenerateWResponse\x129\n" +
	"\x06Verify\x12\x16.captcha.VerifyRequest\x1a\x17.captcha.VerifyResponse\x12<\n" +
	"\aVersion\x12\x17.captcha.VersionRequest\x1a\x18.captcha.VersionResponse2\xaf\x04\n" +
	"\fSlideService\x12R\n" +
	"\x05Solve\x12#.captcha.SolveGeetestCaptchaRequest\x1a$.captcha.SolveGeetestCaptchaResponse\x126\n" +
	"\x05GetCS\x12\x15.captcha.GetCSRequest\x1a\x16.captcha.GetCSResponse\x12<\n" +
	"\aGetType\x12\x17.captcha.GetTypeRequest\x1a\x18.captcha.GetTypeResponse\x12K\n" +
	"\fGetNewCSArgs\x12\x1c.captcha.GetNewCSArgsRequest\x1a\x1d.captcha.GetNewCSArgsResponse\x12K\n" +
	"\fCalculateKey\x12\x1c.captcha.CalculateKeyRequest\x1a\x1d.captcha.CalculateKeyResponse\x12B\n" +
	"\tGenerateW\x12\x19.captcha.GenerateWRequest\x1a\x1a.captcha.GenerateWResponse\x129\n" +
	"\x06Verify\x12\x16.captcha.VerifyRequest\x1a\x17.captcha.VerifyResponse\x12<\n" +
	"\aVersion\x12\x17.captcha.VersionRequest\x1a\x18.captcha.VersionResponseB\vZ\t./captchab\x06proto3"

var (
	file_captcha_proto_rawDescOnce sync.Once
	file_captcha_proto_rawDescData []byte
)

func file_captcha_proto_rawDescGZIP() []byte {
	file_captcha_proto_rawDescOnce.Do(func() {
		file_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_captcha_proto_rawDesc), len(file_captcha_proto_rawDesc)))
	})
	return file_captcha_proto_rawDescData
}

var file_captcha_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_captcha_proto_goTypes = []any{
	(CaptchaType)(0),                    // 0: captcha.CaptchaType
	(*GeetestCS)(nil),                   // 1: captcha.GeetestCS
	(*NewCSArgs)(nil),                   // 2: captcha.NewCSArgs
	(*SolveGeetestCaptchaRequest)(nil),  // 3: captcha.SolveGeetestCaptchaRequest
	(*SolveGeetestCaptchaResponse)(nil), // 4: captcha.SolveGeetestCaptchaResponse
	(*GetCSRequest)(nil),                // 5: captcha.GetCSRequest
	(*GetCSResponse)(nil),               // 6: captcha.GetCSResponse
	(*GetTypeRequest)(nil),              // 7: captcha.GetTypeRequest
	(*GetTypeResponse)(nil),             // 8: captcha.GetTypeResponse
	(*GetNewCSArgsRequest)(nil),         // 9: captcha.GetNewCSArgsRequest
	(*GetNewCSArgsResponse)(nil),        // 10: captcha.GetNewCSArgsResponse
	(*CalculateKeyRequest)(nil),         // 11: captcha.CalculateKeyRequest
	(*CalculateKeyResponse)(nil),        // 12: captcha.CalculateKeyResponse
	(*GenerateWRequest)(nil),            // 13: captcha.GenerateWRequest
	(*GenerateWResponse)(nil),           // 14: captcha.GenerateWResponse
	(*VerifyRequest)(nil),               // 15: captcha.VerifyRequest
	(*VerifyResponse)(nil),              // 16: captcha.VerifyResponse
	(*VersionRequest)(nil),              // 17: captcha.VersionRequest
	(*VersionResponse)(nil),             // 18: captcha.VersionResponse
}
var file_captcha_proto_depIdxs = []int32{
	1,  // 0: captcha.GetCSResponse.cs:type_name -> captcha.GeetestCS
	0,  // 1: captcha.GetTypeResponse.type:type_name -> captcha.CaptchaType
	2,  // 2: captcha.GetNewCSArgsResponse.args:type_name -> captcha.NewCSArgs
	2,  // 3: captcha.CalculateKeyRequest.args:type_name -> captcha.NewCSArgs
	2,  // 4: captcha.GenerateWRequest.args:type_name -> captcha.NewCSArgs
	3,  // 5: captcha.ClickService.Solve:input_type -> captcha.SolveGeetestCaptchaRequest
	5,  // 6: captcha.ClickService.GetCS:input_type -> captcha.GetCSRequest
	7,  // 7: captcha.ClickService.GetType:input_type -> captcha.GetTypeRequest
	9,  // 8: captcha.ClickService.GetNewCSArgs:input_type -> captcha.GetNewCSArgsRequest
	11, // 9: captcha.ClickService.CalculateKey:input_type -> captcha.CalculateKeyRequest
	13, // 10: captcha.ClickService.GenerateW:input_type -> captcha.GenerateWRequest
	15, // 11: captcha.ClickService.Verify:input_type -> captcha.VerifyRequest
	17, // 12: captcha.ClickService.Version:input_type -> captcha.VersionRequest
	3,  // 13: captcha.SlideService.Solve:input_type -> captcha.SolveGeetestCaptchaRequest
	5,  // 14: captcha.SlideService.GetCS:input_type -> captcha.GetCSRequest
	7,  // 15: captcha.SlideService.GetType:input_type -> captcha.GetTypeRequest
	9,  // 16: captcha.SlideService.GetNewCSArgs:input_type -> captcha.GetNewCSArgsRequest
	11, // 17: captcha.SlideService.CalculateKey:input_type -> captcha.CalculateKeyRequest
	13, // 18: captcha.SlideService.GenerateW:input_type -> captcha.GenerateWRequest
	15, // 19: captcha.SlideService.Verify:input_type -> captcha.VerifyRequest
	17, // 20: captcha.SlideService.Version:input_type -> captcha.VersionRequest
	4,  // 21: captcha.ClickService.Solve:output_type -> captcha.SolveGeetestCaptchaResponse
	6,  // 22: captcha.ClickService.GetCS:output_type -> captcha.GetCSResponse
	8,  // 23: captcha.ClickService.GetType:output_type -> captcha.GetTypeResponse
	10, // 24: captcha.ClickService.GetNewCSArgs:output_type -> captcha.GetNewCSArgsResponse
	12, // 25: captcha.ClickService.CalculateKey:output_type -> captcha.CalculateKeyResponse
	14, // 26: captcha.ClickService.GenerateW:output_type -> captcha.GenerateWResponse
	16, // 27: captcha.ClickService.Verify:output_type -> captcha.VerifyResponse
	18, // 28: captcha.ClickService.Version:output_type -> captcha.VersionResponse
	4,  // 29: captcha.SlideService.Solve:output_type -> captcha.SolveGeetestCaptchaResponse
	6,  // 30: captcha.SlideService.GetCS:output_type -> captcha.GetCSResponse
	8,  // 31: captcha.SlideService.GetType:output_type -> captcha.GetTypeResponse
	10, // 32: captcha.SlideService.GetNewCSArgs:output_type -> captcha.GetNewCSArgsResponse
	12, // 33: captcha.SlideService.CalculateKey:output_type -> captcha.CalculateKeyResponse
	14, // 34: captcha.SlideService.GenerateW:output_type -> captcha.GenerateWResponse
	16, // 35: captcha.SlideService.Verify:output_type -> captcha.VerifyResponse
	18, // 36: captcha.SlideService.Version:output_type -> captcha.VersionResponse
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_captcha_proto_init() }
func file_captcha_proto_init() {
	if File_captcha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_captcha_proto_rawDesc), len(file_captcha_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_captcha_proto_goTypes,
		DependencyIndexes: file_captcha_proto_depIdxs,
		EnumInfos:         file_captcha_proto_enumTypes,
		MessageInfos:      file_captcha_proto_msgTypes,
	}.Build()
	File_captcha_proto = out.File
	file_captcha_proto_goTypes = nil
	file_captcha_proto_depIdxs = nil
}
