// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * A CookieJar manages storage and use of cookies in HTTP requests.
 * 
 * Implementations of CookieJar must be safe for concurrent use by multiple
 * goroutines.
 * 
 * The net/http/cookiejar package provides a CookieJar implementation.
 * @typedef {$models.CookieJar} CookieJar
 */
