// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A CookieJar manages storage and use of cookies in HTTP requests.
 * 
 * Implementations of CookieJar must be safe for concurrent use by multiple
 * goroutines.
 * 
 * The net/http/cookiejar package provides a CookieJar implementation.
 * @typedef {any} CookieJar
 */
