// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LoadedPluginInfo {
    /**
     * Creates a new LoadedPluginInfo instance.
     * @param {Partial<LoadedPluginInfo>} [$$source = {}] - The source object to create the LoadedPluginInfo.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("GitCommit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["GitCommit"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("TestResult" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TestResult"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadedPluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadedPluginInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadedPluginInfo(/** @type {Partial<LoadedPluginInfo>} */($$parsedSource));
    }
}

/**
 * PluginAsset is a single downloadable file in a release.
 * It wraps the raw asset and adds parsed platform/arch info.
 */
export class PluginAsset {
    /**
     * Creates a new PluginAsset instance.
     * @param {Partial<PluginAsset>} [$$source = {}] - The source object to create the PluginAsset.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("platform" in $$source)) {
            /**
             * windows / linux / darwin
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * amd64 / arm64
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("platformLabel" in $$source)) {
            /**
             * e.g. "Windows (AMD64)"
             * @member
             * @type {string}
             */
            this["platformLabel"] = "";
        }
        if (!("checksum" in $$source)) {
            /**
             * checksum for integrity verification
             * @member
             * @type {string}
             */
            this["checksum"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginAsset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginAsset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginAsset(/** @type {Partial<PluginAsset>} */($$parsedSource));
    }
}

/**
 * PluginDefinition describes a known plugin that the application can download.
 */
export class PluginDefinition {
    /**
     * Creates a new PluginDefinition instance.
     * @param {Partial<PluginDefinition>} [$$source = {}] - The source object to create the PluginDefinition.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Name is the plugin binary name, e.g. "captcha-plugin".
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * Description is a human-readable summary of the plugin.
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * Source is where the plugin is fetched from.
             * @member
             * @type {PluginSource}
             */
            this["source"] = PluginSource.$zero;
        }
        if (!("repoOwner" in $$source)) {
            /**
             * RepoOwner is the GitHub repository owner (only for SourceGitHub).
             * @member
             * @type {string}
             */
            this["repoOwner"] = "";
        }
        if (!("repoName" in $$source)) {
            /**
             * RepoName is the GitHub repository name (only for SourceGitHub).
             * @member
             * @type {string}
             */
            this["repoName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginDefinition}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginDefinition(/** @type {Partial<PluginDefinition>} */($$parsedSource));
    }
}

/**
 * PluginInfo describes a single downloadable plugin release.
 */
export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Name is the plugin binary name, e.g. "captcha-plugin".
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * Version is the release tag / commit hash.
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * Description from the GitHub release body.
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * PublishedAt is the release publish time (RFC3339).
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (!("assets" in $$source)) {
            /**
             * Assets lists all downloadable files for this release.
             * @member
             * @type {PluginAsset[]}
             */
            this["assets"] = [];
        }
        if (!("source" in $$source)) {
            /**
             * Source is where this plugin was fetched from.
             * @member
             * @type {PluginSource}
             */
            this["source"] = PluginSource.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField4_0($$parsedSource["assets"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

/**
 * PluginListResult is returned to the frontend.
 */
export class PluginListResult {
    /**
     * Creates a new PluginListResult instance.
     * @param {Partial<PluginListResult>} [$$source = {}] - The source object to create the PluginListResult.
     */
    constructor($$source = {}) {
        if (!("plugins" in $$source)) {
            /**
             * @member
             * @type {PluginInfo[]}
             */
            this["plugins"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginListResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField0_0($$parsedSource["plugins"]);
        }
        return new PluginListResult(/** @type {Partial<PluginListResult>} */($$parsedSource));
    }
}

/**
 * PluginSource enumerates where plugins are fetched from.
 * @readonly
 * @enum {string}
 */
export const PluginSource = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SourceGitHub: "github",
};

// Private type creation functions
const $$createType0 = PluginAsset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PluginInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
