// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * multiple plugin management, e.g. captcha, account info, etc.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pcommon$0 from "./pcommon/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../../../github.com/hashicorp/go-plugin/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAllVersions returns version information for all currently loaded plugins.
 * Plugins that don't support versioning are skipped silently.
 * @returns {$CancellablePromise<$models.LoadedPluginInfo[]>}
 */
export function GetAllVersions() {
    return $Call.ByID(2987682670).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<plugin$0.Client | null>}
 */
export function GetClient(name) {
    return $Call.ByID(1906193371, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetVersion retrieves version information from any loaded plugin.
 * The plugin must implement the VersionedPlugin interface.
 * Returns an error if the plugin is not loaded or doesn't support versioning.
 * @param {string} name
 * @returns {$CancellablePromise<pcommon$0.VersionInfo>}
 */
export function GetVersion(name) {
    return $Call.ByID(1817964336, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLoaded(name) {
    return $Call.ByID(1996007861, name);
}

/**
 * RegisterPlugin registers a plugin instance with the manager.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function LoadPlugin(name) {
    return $Call.ByID(2816036271, name);
}

/**
 * SetTestResult saves a test result string for the plugin.
 * @param {string} name
 * @param {string} result
 * @returns {$CancellablePromise<void>}
 */
export function SetTestResult(name, result) {
    return $Call.ByID(1803055597, name, result);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnloadAll() {
    return $Call.ByID(2556206054);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UnloadPlugin(name) {
    return $Call.ByID(899693912, name);
}

// Private type creation functions
const $$createType0 = $models.LoadedPluginInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = plugin$0.Client.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = pcommon$0.VersionInfo.createFrom;
